import { useState, useEffect, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../contexts/AuthContext";
import { supabase } from "../lib/supabase";
import ProTierBanner from "../components/ProTierBanner";

const BASE = "https://virenn77-spacedebrisai.hf.space";
const LS_KEY   = "sdai_guest_api_key";
const LS_EMAIL = "sdai_guest_email";
const PUBLIC_OBJECT_COUNT = 2000;
const CACHED_DEBRIS_COUNT = "33k+";
const PAID_OBJECT_COUNT = "10k+";
const PAID_PRICE = "$10";
const PAID_POLLING = "5s";

const ENDPOINTS = [
  {
    method: "GET", path: "/health", auth: false,
    desc: "Check whether the SpaceDebrisAI backend is online and healthy.",
    response: { status: "ok", version: "2.0.0" },
  },
  {
    method: "GET", path: "/satellites", auth: true,
    desc: "Real-time geodetic positions (lat, lon, altitude) for the current public slice, propagated with SGP4 from the local 33k+ debris TLE catalog.",
    response: { count: 414, errors: 0, timestamp: "2026-03-11T10:00:00.000Z", satellites: [{ name: "THOR ABLESTAR DEB", lat: 24.18, lon: 109.33, alt_km: 455.8 }] },
  },
  {
    method: "GET", path: "/simulate", auth: true,
    desc: "Full proximity simulation across the same 2000-object public slice. Returns positions, 20 closest approach pairs, AI risk classifications (CRITICAL / MEDIUM / LOW), and recommended avoidance maneuvers.",
    response: { mode: "local", meta: { satellites: 487, public_objects: 2000, tle_records: 33338, tle_source: "cache", pairs_checked: 118341, processing_ms: 742.6 }, closest_pairs: [{ satellites: ["THOR ABLESTAR DEB", "SL-8 DEB"], before: { distance_km: 3.12, risk: { level: "CRITICAL", score: 0.97 } }, after: { distance_km: 28.4, risk: { level: "LOW", score: 0.12 } }, maneuver: "Raise apogee by 500 m" }] },
  },
  {
    method: "GET", path: "/tracker/positions", auth: true,
    desc: "Propagated orbital positions for the current tracker slice, served directly from the backend TLE cache with no browser-side external API calls.",
    response: { source: "cache", satellites: [{ noradId: 25544, name: "ISS (ZARYA)", lat: 51.62, lon: -12.4, alt: 408.5, azimuth: null, elevation: null }] },
  },
  {
    method: "GET", path: "/docs", auth: false, isLink: true,
    desc: "Interactive Swagger / OpenAPI documentation auto-generated by FastAPI. Try every endpoint directly in your browser.",
    response: null,
  },
];

const METHOD_COLOR = { GET: "#22c55e", POST: "#38bdf8", DELETE: "#ef4444" };
const HERO_STATS = [
  { value: String(PUBLIC_OBJECT_COUNT), label: "public objects" },
  { value: CACHED_DEBRIS_COUNT, label: "cached debris tles" },
  { value: PAID_PRICE, label: "paid tier" },
  { value: PAID_POLLING, label: "paid polling" },
];
const PREMIUM_API_HIGHLIGHTS = [
  { value: PAID_OBJECT_COUNT, label: "objects" },
  { value: PAID_PRICE, label: "per month" },
  { value: PAID_POLLING, label: "max polling" },
];

const LANG_CODE = {
  python: (key) => `import requests

API_KEY = "${key}"
BASE    = "${BASE}"
HEADERS = {"X-API-Key": API_KEY}

# Public 2000-object snapshot
r = requests.get(f"{BASE}/satellites", headers=HEADERS)
sats = r.json()["satellites"]
for s in sats[:5]:
    print(f"{s['name']:30s}  lat={s['lat']:8.3f}  alt={s['alt_km']:.1f} km")

# Proximity simulation
sim = requests.get(f"{BASE}/simulate", headers=HEADERS).json()
for pair in sim["closest_pairs"][:3]:
    a, b = pair["satellites"]
    d    = pair["before"]["distance_km"]
    lvl  = pair["before"]["risk"]["level"]
    print(f"{a} <> {b}: {d:.1f} km  [{lvl}]")`,

  javascript: (key) => `const BASE    = "${BASE}";
const API_KEY = "${key}";
const headers = { "X-API-Key": API_KEY };

// Public 2000-object snapshot
const { satellites } = await fetch(\`\${BASE}/satellites\`, { headers }).then(r => r.json());
satellites.slice(0, 5).forEach(s =>
  console.log(s.name, s.lat, s.lon, s.alt_km + " km")
);

// Proximity simulation
const sim = await fetch(\`\${BASE}/simulate\`, { headers }).then(r => r.json());
sim.closest_pairs.slice(0, 3).forEach(({ satellites: [a, b], before }) =>
  console.log(\`\${a} <> \${b}: \${before.distance_km} km [\${before.risk.level}]\`)
);`,

  curl: (key) => `# Health check (no auth needed)
curl ${BASE}/health

# Public 2000-object snapshot
curl -H "X-API-Key: ${key}" \\
     ${BASE}/satellites | jq '.satellites[:5]'

# Full proximity simulation
curl -H "X-API-Key: ${key}" \\
     ${BASE}/simulate | jq '{mode,meta,closest_pairs:.closest_pairs[:3]}'`,
};

function mkKey(seed) {
  const ts  = Date.now().toString(16).slice(-8);
  const rnd = Math.floor(Math.random() * 0xffffffffffff).toString(16).padStart(12, "0");
  const uid = seed.replace(/[^a-z0-9]/gi, "").slice(0, 8).padEnd(8, "0");
  return `sdai_${uid}${ts}${rnd}_live`;
}

const PremiumApiAnnouncement = ProTierBanner;

export default function ApiPage() {
  const { user, loading: authLoading, signOut } = useAuth();
  const navigate = useNavigate();

  // ── Supabase key state (logged-in users) ──────────────────────
  const [apiKey, setApiKey]         = useState("");
  const [keyId, setKeyId]           = useState(null);
  const [keyLoading, setKeyLoading] = useState(false);
  const [keyError, setKeyError]     = useState("");
  const [revokeConfirm, setRevokeConfirm] = useState(false);

  // ── Guest / no-login state ────────────────────────────────────
  const [guestKey, setGuestKey]           = useState(() => localStorage.getItem(LS_KEY) || "");
  const [guestEmail, setGuestEmail]       = useState(() => localStorage.getItem(LS_EMAIL) || "");
  const [showWarnModal, setShowWarnModal] = useState(false);
  const [emailInput, setEmailInput]       = useState("");
  const [emailError, setEmailError]       = useState("");

  // ── UI state ──────────────────────────────────────────────────
  const [copied, setCopied]         = useState(false);
  const [expanded, setExpanded]     = useState({});
  const [codeLang, setCodeLang]     = useState("python");
  const [codeCopied, setCodeCopied] = useState(false);

  // effective key & email for display / code examples
  const activeKey   = user ? apiKey : guestKey;
  const activeEmail = user ? user.email : guestEmail;
  const hasAccess   = !!user || !!guestKey;

  const loadKey = useCallback(async () => {
    if (!user || !supabase) return;
    const { data } = await supabase
      .from("api_keys")
      .select("id, key")
      .eq("user_id", user.id)
      .eq("active", true)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();
    if (data) { setApiKey(data.key); setKeyId(data.id); }
  }, [user]);

  useEffect(() => { loadKey(); }, [loadKey]);

  // ── Guest key generation ──────────────────────────────────────
  function handleContinueWithoutLogin() {
    setShowWarnModal(true);
  }

  function handleGuestGenerate() {
    const trimmed = emailInput.trim();
    if (!trimmed || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(trimmed)) {
      setEmailError("Please enter a valid email address.");
      return;
    }
    const newKey = mkKey(trimmed);
    localStorage.setItem(LS_KEY, newKey);
    localStorage.setItem(LS_EMAIL, trimmed);
    setGuestKey(newKey);
    setGuestEmail(trimmed);
    setShowWarnModal(false);
    setEmailInput("");
    setEmailError("");
  }

  function handleGuestRevoke() {
    localStorage.removeItem(LS_KEY);
    localStorage.removeItem(LS_EMAIL);
    setGuestKey(""); setGuestEmail("");
  }

  // ── Supabase key actions ──────────────────────────────────────
  async function handleGenerateKey() {
    if (!supabase) return;
    setKeyLoading(true); setKeyError("");
    const newKey = mkKey(user.id);
    const { data, error } = await supabase.from("api_keys")
      .insert({ user_id: user.id, key: newKey, active: true })
      .select("id, key").single();
    if (error) { setKeyError(error.message); setKeyLoading(false); return; }
    setApiKey(data.key); setKeyId(data.id); setKeyLoading(false);
  }

  async function handleRegenerate() {
    if (!supabase) return;
    setKeyLoading(true); setKeyError("");
    if (keyId) await supabase.from("api_keys").update({ active: false }).eq("id", keyId);
    const newKey = mkKey(user.id);
    const { data, error } = await supabase.from("api_keys")
      .insert({ user_id: user.id, key: newKey, active: true })
      .select("id, key").single();
    if (error) { setKeyError(error.message); setKeyLoading(false); return; }
    setApiKey(data.key); setKeyId(data.id); setRevokeConfirm(false); setKeyLoading(false);
  }

  async function handleRevoke() {
    if (supabase && keyId) await supabase.from("api_keys").update({ active: false }).eq("id", keyId);
    setApiKey(""); setKeyId(null); setRevokeConfirm(false);
  }

  function copy(text, setter) {
    navigator.clipboard.writeText(text).then(() => { setter(true); setTimeout(() => setter(false), 2000); });
  }

  const displayKey = activeKey || "sdai_xxxxxxxxxxxxxxxxxxxxxxxx_live";
  const heroPreviewKey = activeKey
    ? `${activeKey.slice(0, 18)}...`
    : "sdai_demo_key_live";

  if (authLoading) return (
    <div className="ap-loading-gate"><div className="spinner" /><p>Loading...</p></div>
  );

  return (
    <div className="ap-root">

      {/* ── Warning modal ─────────────────────────────────── */}
      {showWarnModal && (
        <div className="ap-modal-overlay" onClick={() => setShowWarnModal(false)}>
          <div className="ap-modal" onClick={e => e.stopPropagation()}>
            <div className="ap-modal-icon">⚠️</div>
            <h3 className="ap-modal-title">Your key won't be saved to our servers</h3>
            <p className="ap-modal-body">
              Without an account, your API key is stored <strong>only in this browser</strong>.
              If you clear your browser data, uninstall, or switch devices — <strong>the key is gone forever</strong> and cannot be recovered.
            </p>
            <p className="ap-modal-body">Enter your email so you can identify this key. We will not spam you.</p>
            <input
              className={`ap-modal-input${emailError ? " ap-input-error" : ""}`}
              type="email"
              placeholder="you@example.com"
              value={emailInput}
              onChange={e => { setEmailInput(e.target.value); setEmailError(""); }}
              onKeyDown={e => e.key === "Enter" && handleGuestGenerate()}
            />
            {emailError && <p className="ap-modal-error">{emailError}</p>}
            <div className="ap-modal-actions">
              <button className="ap-btn-primary" onClick={handleGuestGenerate}>Generate my API key</button>
              <button className="ap-btn-text" onClick={() => { setShowWarnModal(false); setEmailError(""); }}>Cancel</button>
            </div>
            <p className="ap-modal-login-hint">
              Want your key saved safely?{" "}
              <button className="ap-link-btn" onClick={() => { setShowWarnModal(false); navigate("/login", { state: { from: "/api" } }); }}>
                Sign in / Sign up free →
              </button>
            </p>
          </div>
        </div>
      )}

      {/* ── Hero ─────────────────────────────────────────── */}
      <div className="ap-hero">
        <div className="ap-hero-glow ap-glow-1" />
        <div className="ap-hero-glow ap-glow-2" />
        <div className="ap-hero-inner">
          <div className="ap-hero-grid">
            <div className="ap-hero-copy">
              <p className="ap-eyebrow">Developer Access</p>
              <h1 className="ap-h1">SpaceDebrisAI<br /><span className="ap-h1-accent">Public API</span></h1>
              <p className="ap-sub">
                Real-time orbital positions, conjunction screening, and AI-generated avoidance
                maneuvers through a clean REST interface. The public tier currently serves a
                <strong style={{ color: "var(--text-bright)" }}> 2000-object propagated slice</strong>,
                backed by a <strong style={{ color: "var(--text-bright)" }}> 33k+ local TLE record catalog</strong>
                refreshed from KeepTrack once per hour.
              </p>
              <div className="ap-badges">
                <span className="ap-badge">REST</span>
                <span className="ap-badge">JSON</span>
                <span className="ap-badge">Free + guest keys</span>
                <span className="ap-badge ap-badge-live">KeepTrack cache</span>
              </div>
              <div className="ap-hero-actions">
                <a className="ap-btn-primary ap-hero-btn" href="#api-key-section">
                  {hasAccess ? "View your API key" : "Get free API key"}
                </a>
                <a
                  className="ap-btn-outline ap-hero-btn"
                  href={`${BASE}/docs`}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Open Swagger
                </a>
              </div>
              {activeEmail && (
                <div className="ap-user-pill">
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><circle cx="7" cy="4.5" r="2.5" stroke="currentColor" strokeWidth="1.3"/><path d="M1.5 12.5c0-3.036 2.462-5.5 5.5-5.5s5.5 2.464 5.5 5.5" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/></svg>
                  <span className="ap-user-pill-email">{activeEmail}</span>
                  {user
                    ? <button className="ap-signout-btn" onClick={signOut}>Sign out</button>
                    : <button className="ap-signout-btn" onClick={handleGuestRevoke}>Clear key</button>
                  }
                  {!user && <span className="ap-guest-badge">Guest</span>}
                </div>
              )}
            </div>

            <div className="ap-hero-panel">
              <div className="ap-hero-panel-top">
                <span className="ap-hero-panel-label">Build faster</span>
                <span className="ap-badge ap-badge-live">Production-ready docs</span>
              </div>

              <div className="ap-hero-kpis">
                {HERO_STATS.map((stat) => (
                  <div key={stat.label} className="ap-hero-kpi">
                    <span className="ap-hero-kpi-value">{stat.value}</span>
                    <span className="ap-hero-kpi-label">{stat.label}</span>
                  </div>
                ))}
              </div>

              <div className="ap-hero-request">
                <p className="ap-label">Quick request</p>
                <pre className="ap-pre ap-hero-pre">{`curl -H "X-API-Key: ${heroPreviewKey}" \\
  ${BASE}/simulate`}</pre>
              </div>

              <div className="ap-hero-list">
                <div className="ap-hero-list-item">Saved account keys or instant browser-only guest access</div>
                <div className="ap-hero-list-item">Public responses cover 500 propagated objects from the current hourly cache</div>
                <div className="ap-hero-list-item">Paid tier announced for 10k+ objects with 5-second polling</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="ap-body">

        {/* ── 01 API key ───────────────────────────────────── */}
        <section className="ap-section" id="api-key-section">
          <div className="ap-section-label-row">
            <span className="ap-section-num">01</span>
            <div className="ap-section-heading">
              <h2 className="ap-section-title">Your API key</h2>
              <p className="ap-section-copy">Choose a saved account key or generate a browser-only guest key for immediate testing on the public 2000-object tier.</p>
            </div>
          </div>

          {/* ── Not logged in, no guest key: choice gate ── */}
          {!hasAccess && (
            <div className="ap-choice-gate">
              {/* Option A — Sign in */}
              <div className="ap-cg-option ap-cg-primary">
                <div className="ap-cg-top">
                  <div className="ap-cg-icon-wrap ap-cg-icon-blue">
                    <svg width="22" height="22" viewBox="0 0 22 22" fill="none">
                      <rect x="3" y="11" width="16" height="10" rx="2.5" stroke="#38bdf8" strokeWidth="1.5"/>
                      <path d="M7 11V7.5a4 4 0 0 1 8 0V11" stroke="#38bdf8" strokeWidth="1.5" strokeLinecap="round"/>
                      <circle cx="11" cy="16" r="1.5" fill="#38bdf8"/>
                    </svg>
                  </div>
                  <span className="ap-cg-rec-pill">Recommended</span>
                </div>
                <h3 className="ap-cg-title">Sign in free</h3>
                <p className="ap-cg-body">Your key is permanently saved to your account. Access it from any device, regenerate it anytime, and never lose it.</p>
                <ul className="ap-cg-perks">
                  <li><span className="ap-cg-check">✓</span> Key persisted to your account</li>
                  <li><span className="ap-cg-check">✓</span> Works across all devices</li>
                  <li><span className="ap-cg-check">✓</span> Regenerate &amp; revoke anytime</li>
                </ul>
                <button className="ap-btn-primary ap-cg-btn" onClick={() => navigate("/login", { state: { from: "/api" } })}>
                  Sign in / Create free account
                </button>
                <p className="ap-cg-note">Free public tier. No credit card.</p>
              </div>

              <div className="ap-cg-divider">
                <span>or</span>
              </div>

              {/* Option B — Guest */}
              <div className="ap-cg-option ap-cg-guest">
                <div className="ap-cg-top">
                  <div className="ap-cg-icon-wrap ap-cg-icon-amber">
                    <svg width="22" height="22" viewBox="0 0 22 22" fill="none">
                      <path d="M11 2 L13.5 8.5 H20.5 L14.5 12.5 L16.5 19 L11 15 L5.5 19 L7.5 12.5 L1.5 8.5 H8.5 Z" stroke="#f59e0b" strokeWidth="1.4" strokeLinejoin="round"/>
                    </svg>
                  </div>
                </div>
                <h3 className="ap-cg-title">Quick access</h3>
                <p className="ap-cg-body">Get a key instantly without signing up. Stored only in this browser — if you clear site data, the key is gone.</p>
                <ul className="ap-cg-perks ap-cg-perks-warn">
                  <li><span className="ap-cg-warn">⚠</span> Browser storage only</li>
                  <li><span className="ap-cg-warn">⚠</span> Lost if you clear data</li>
                  <li><span className="ap-cg-check">✓</span> No account needed</li>
                </ul>
                <button className="ap-btn-outline ap-cg-btn" onClick={handleContinueWithoutLogin}>
                  Continue without account
                </button>
              </div>
            </div>
          )}

          {/* ── Logged in: Supabase-backed key ── */}
          {user && (
            <div className="ap-key-card">
              <PremiumApiAnnouncement />
              {keyError && <p className="ap-key-error">{keyError}</p>}
              {!apiKey ? (
                <div className="ap-key-empty">
                  <div className="ap-key-placeholder-icon">
                    <svg width="40" height="40" viewBox="0 0 40 40" fill="none"><circle cx="15" cy="15" r="9" stroke="var(--accent)" strokeWidth="1.5"/><circle cx="15" cy="15" r="4" fill="none" stroke="var(--accent)" strokeWidth="1.5"/><path d="M21.5 21.5 L35 35" stroke="var(--accent)" strokeWidth="2" strokeLinecap="round"/><circle cx="29" cy="31" r="2" fill="var(--accent)" opacity="0.6"/><circle cx="33" cy="35" r="1.5" fill="var(--accent)" opacity="0.4"/></svg>
                  </div>
                  <p className="ap-key-empty-text">No API key yet. Generate one to start making live requests.</p>
                  <button className="ap-btn-primary ap-key-gen-btn" onClick={handleGenerateKey} disabled={keyLoading}>
                    {keyLoading ? <span className="btn-spinner" /> : "Generate API key"}
                  </button>
                </div>
              ) : (
                <>
                  <p className="ap-key-intro">Include as <code className="ap-inline-code">X-API-Key</code> header on every authenticated request.</p>
                  <div className="ap-key-display">
                    <div className="ap-key-active-dot" />
                    <span className="ap-key-value">{apiKey}</span>
                    <button className={`ap-btn-copy${copied ? " copied" : ""}`} onClick={() => copy(apiKey, setCopied)}>
                      {copied ? "Copied ✓" : "Copy"}
                    </button>
                  </div>
                  <div className="ap-key-meta">
                    <span className="ap-key-meta-item"><span className="ap-dot ap-dot-green" />Active</span>
                    <span className="ap-key-meta-sep">·</span>
                    <span className="ap-key-meta-item ap-key-meta-email">{user.email}</span>
                  </div>
                  <div className="ap-key-actions">
                    <button className="ap-btn-regen" onClick={handleRegenerate} disabled={keyLoading}>
                      {keyLoading ? <span className="btn-spinner" /> : "↻ Regenerate"}
                    </button>
                    {!revokeConfirm ? (
                      <button className="ap-btn-revoke" onClick={() => setRevokeConfirm(true)}>Revoke key</button>
                    ) : (
                      <div className="ap-revoke-confirm">
                        <span className="ap-revoke-warn">This will delete your key permanently.</span>
                        <button className="ap-btn-revoke-confirm" onClick={handleRevoke}>Yes, revoke</button>
                        <button className="ap-btn-text" onClick={() => setRevokeConfirm(false)}>Cancel</button>
                      </div>
                    )}
                  </div>
                </>
              )}
            </div>
          )}

          {/* ── Guest key active ── */}
          {!user && guestKey && (
            <div className="ap-key-card">
              {/* Banner */}
              <div className="ap-guest-banner">
                <div className="ap-guest-banner-left">
                  <span className="ap-guest-banner-icon">⚠️</span>
                  <div>
                    <strong>Guest key — browser only</strong>
                    <p>This key lives only in this browser. Clear site data and it's gone permanently.</p>
                  </div>
                </div>
                <button className="ap-guest-upgrade-btn" onClick={() => navigate("/login", { state: { from: "/api" } })}>
                  Save to account →
                </button>
              </div>

              <PremiumApiAnnouncement />
              <p className="ap-key-intro">Include as <code className="ap-inline-code">X-API-Key</code> header on every authenticated request.</p>
              <div className="ap-key-display">
                <div className="ap-key-active-dot" style={{background:"#f59e0b"}} />
                <span className="ap-key-value">{guestKey}</span>
                <button className={`ap-btn-copy${copied ? " copied" : ""}`} onClick={() => copy(guestKey, setCopied)}>
                  {copied ? "Copied ✓" : "Copy"}
                </button>
              </div>
              <div className="ap-key-meta">
                <span className="ap-key-meta-item">
                  <span className="ap-dot" style={{background:"#f59e0b"}} />
                  <span className="ap-guest-badge">Guest</span>
                </span>
                <span className="ap-key-meta-sep">·</span>
                <span className="ap-key-meta-item ap-key-meta-email">{guestEmail}</span>
              </div>
              <div className="ap-key-actions">
                <button className="ap-btn-regen" onClick={() => { handleGuestRevoke(); setShowWarnModal(true); }}>↻ Regenerate</button>
                <button className="ap-btn-revoke" onClick={handleGuestRevoke}>Clear key</button>
              </div>
            </div>
          )}
        </section>

        {/* ── 02 Base URL ──────────────────────────────────── */}
        <section className="ap-section">
          <div className="ap-section-label-row">
            <span className="ap-section-num">02</span>
            <div className="ap-section-heading">
              <h2 className="ap-section-title">Base URL</h2>
              <p className="ap-section-copy">All requests run over HTTPS with the same header convention across the public tier and the announced paid tier.</p>
            </div>
          </div>
          <div className="ap-base-url-card">
            <span className="ap-env-pill">PRODUCTION</span>
            <code className="ap-base-code">{BASE}</code>
            <p className="ap-base-note">All endpoints use HTTPS. Pass your key via <code className="ap-inline-code">X-API-Key</code> header.</p>
          </div>
        </section>

        {/* ── 03 Endpoints ─────────────────────────────────── */}
        <section className="ap-section">
          <div className="ap-section-label-row">
            <span className="ap-section-num">03</span>
            <div className="ap-section-heading">
              <h2 className="ap-section-title">Endpoints</h2>
              <p className="ap-section-copy">Browse the current public API surface, inspect payloads, and see how the 2000-object slice is exposed today.</p>
            </div>
          </div>
          <div className="ap-endpoints">
            {ENDPOINTS.map((ep) => (
              <div key={ep.path} className={`ap-endpoint${expanded[ep.path] ? " ap-endpoint--open" : ""}`}>
                <button className="ap-endpoint-header" onClick={() => setExpanded(p => ({...p, [ep.path]: !p[ep.path]}))}>
                  <span className="ap-method" style={{color: METHOD_COLOR[ep.method]}}>{ep.method}</span>
                  <span className="ap-path">{ep.path}</span>
                  <span className="ap-endpoint-desc-short">{ep.desc.split(".")[0]}.</span>
                  {ep.auth && <span className="ap-auth-badge" title="Requires X-API-Key">🔑</span>}
                  <span className="ap-expand-icon">{expanded[ep.path] ? "−" : "+"}</span>
                </button>
                {expanded[ep.path] && (
                  <div className="ap-endpoint-body">
                    <p className="ap-endpoint-full-desc">{ep.desc}</p>
                    {ep.auth && (
                      <div className="ap-endpoint-auth-note">
                        Header: <code className="ap-inline-code">X-API-Key: {displayKey}</code>
                      </div>
                    )}
                    {ep.isLink
                      ? <a href={`${BASE}${ep.path}`} target="_blank" rel="noopener noreferrer" className="ap-btn-primary ap-docs-btn">Open Swagger UI →</a>
                      : <><p className="ap-label">Example response</p><pre className="ap-pre">{JSON.stringify(ep.response, null, 2)}</pre></>
                    }
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* ── 04 Code examples ─────────────────────────────── */}
        <section className="ap-section">
          <div className="ap-section-label-row">
            <span className="ap-section-num">04</span>
            <div className="ap-section-heading">
              <h2 className="ap-section-title">Code examples</h2>
              <p className="ap-section-copy">Copy a starter request in the language you want and drop in your key for the public tier.</p>
            </div>
          </div>
          <div className="ap-code-card">
            <div className="ap-code-tabs">
              {["python", "javascript", "curl"].map((lang) => (
                <button key={lang} className={`ap-code-tab${codeLang === lang ? " active" : ""}`} onClick={() => setCodeLang(lang)}>{lang}</button>
              ))}
              <button className="ap-btn-copy ap-code-copy" onClick={() => copy(LANG_CODE[codeLang](displayKey), setCodeCopied)}>
                {codeCopied ? "Copied ✓" : "Copy"}
              </button>
            </div>
            <pre className="ap-pre ap-code-body">{LANG_CODE[codeLang](displayKey)}</pre>
          </div>
        </section>

        {/* ── 05 Rate limits ───────────────────────────────── */}
        <section className="ap-section">
          <div className="ap-section-label-row">
            <span className="ap-section-num">05</span>
            <div className="ap-section-heading">
              <h2 className="ap-section-title">Access tiers &amp; fair use</h2>
              <p className="ap-section-copy">The public tier stays lightweight for demos and prototypes, while the announced paid tier targets larger debris coverage and faster polling.</p>
            </div>
          </div>
          <div className="ap-limits-card">
              <div className="ap-limits-grid">
                <div className="ap-limit-item"><span className="ap-limit-val">60</span><span className="ap-limit-label">req / min</span></div>
                <div className="ap-limit-item"><span className="ap-limit-val">500</span><span className="ap-limit-label">public objects</span></div>
                <div className="ap-limit-item"><span className="ap-limit-val">33k+</span><span className="ap-limit-label">cached tle records</span></div>
                <div className="ap-limit-item"><span className="ap-limit-val">$10</span><span className="ap-limit-label">paid tier announced</span></div>
              </div>
            <p className="ap-limits-note">Public requests serve the current 2000-object slice from the local 33k+ TLE catalog. The announced paid tier expands access to 10k+ objects with a 5-second maximum polling cadence.</p>
          </div>
        </section>

      </div>
    </div>
  );
}
