import { useState, useEffect, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../contexts/AuthContext";
import { supabase } from "../lib/supabase";

const BASE = "https://virenn77-spacedebrisai.hf.space";
const LS_KEY   = "sdai_guest_api_key";
const LS_EMAIL = "sdai_guest_email";

const ENDPOINTS = [
  {
    method: "GET", path: "/health", auth: false,
    desc: "Check whether the SpaceDebrisAI backend is online and healthy.",
    response: { status: "ok", version: "2.0.0" },
  },
  {
    method: "GET", path: "/satellites", auth: true,
    desc: "Real-time geodetic positions (lat, lon, altitude) for all 500 tracked satellites via SGP4 orbital propagation from the onboard TLE database.",
    response: { count: 500, errors: 0, timestamp: "2026-03-11T10:00:00.000Z", satellites: [{ name: "ISS (ZARYA)", lat: 51.62, lon: -12.4, alt_km: 408.5 }] },
  },
  {
    method: "GET", path: "/simulate", auth: true,
    desc: "Full proximity simulation across all 500 tracked satellites. Returns positions, 20 closest approach pairs, AI risk classifications (CRITICAL / MEDIUM / LOW), and recommended avoidance maneuvers.",
    response: { mode: "live", meta: { satellites: 500, pairs_checked: 124750, processing_ms: 312.8 }, closest_pairs: [{ satellites: ["ISS (ZARYA)", "PROGRESS MS-24"], before: { distance_km: 3.12, risk: { level: "CRITICAL", score: 0.97 } }, after: { distance_km: 28.4, risk: { level: "LOW", score: 0.12 } }, maneuver: "Raise apogee by 500 m" }] },
  },
  {
    method: "GET", path: "/tracker/positions", auth: true,
    desc: "Live orbital positions for 20 tracked satellites fetched from N2YO API with 2-minute cache. Includes azimuth and elevation angles.",
    response: { source: "live", satellites: [{ noradId: 25544, name: "ISS (ZARYA)", lat: 51.62, lon: -12.4, alt: 408.5, azimuth: 220.3, elevation: 34.1 }] },
  },
  {
    method: "GET", path: "/docs", auth: false, isLink: true,
    desc: "Interactive Swagger / OpenAPI documentation auto-generated by FastAPI. Try every endpoint directly in your browser.",
    response: null,
  },
];

const METHOD_COLOR = { GET: "#22c55e", POST: "#38bdf8", DELETE: "#ef4444" };

const LANG_CODE = {
  python: (key) => `import requests

API_KEY = "${key}"
BASE    = "${BASE}"
HEADERS = {"X-API-Key": API_KEY}

# All 500 satellite positions
r = requests.get(f"{BASE}/satellites", headers=HEADERS)
sats = r.json()["satellites"]
for s in sats[:5]:
    print(f"{s['name']:30s}  lat={s['lat']:8.3f}  alt={s['alt_km']:.1f} km")

# Proximity simulation
sim = requests.get(f"{BASE}/simulate", headers=HEADERS).json()
for pair in sim["closest_pairs"][:3]:
    a, b = pair["satellites"]
    d    = pair["before"]["distance_km"]
    lvl  = pair["before"]["risk"]["level"]
    print(f"{a} <> {b}: {d:.1f} km  [{lvl}]")`,

  javascript: (key) => `const BASE    = "${BASE}";
const API_KEY = "${key}";
const headers = { "X-API-Key": API_KEY };

// All 500 satellite positions
const { satellites } = await fetch(\`\${BASE}/satellites\`, { headers }).then(r => r.json());
satellites.slice(0, 5).forEach(s =>
  console.log(s.name, s.lat, s.lon, s.alt_km + " km")
);

// Proximity simulation
const sim = await fetch(\`\${BASE}/simulate\`, { headers }).then(r => r.json());
sim.closest_pairs.slice(0, 3).forEach(({ satellites: [a, b], before }) =>
  console.log(\`\${a} <> \${b}: \${before.distance_km} km [\${before.risk.level}]\`)
);`,

  curl: (key) => `# Health check (no auth needed)
curl ${BASE}/health

# 500 satellite positions
curl -H "X-API-Key: ${key}" \\
     ${BASE}/satellites | jq '.satellites[:5]'

# Full proximity simulation
curl -H "X-API-Key: ${key}" \\
     ${BASE}/simulate | jq '{mode,meta,closest_pairs:.closest_pairs[:3]}'`,
};

function mkKey(seed) {
  const ts  = Date.now().toString(16).slice(-8);
  const rnd = Math.floor(Math.random() * 0xffffffffffff).toString(16).padStart(12, "0");
  const uid = seed.replace(/[^a-z0-9]/gi, "").slice(0, 8).padEnd(8, "0");
  return `sdai_${uid}${ts}${rnd}_live`;
}

export default function ApiPage() {
  const { user, loading: authLoading, signOut } = useAuth();
  const navigate = useNavigate();

  // ── Supabase key state (logged-in users) ──────────────────────
  const [apiKey, setApiKey]         = useState("");
  const [keyId, setKeyId]           = useState(null);
  const [keyLoading, setKeyLoading] = useState(false);
  const [keyError, setKeyError]     = useState("");
  const [revokeConfirm, setRevokeConfirm] = useState(false);

  // ── Guest / no-login state ────────────────────────────────────
  const [guestKey, setGuestKey]           = useState(() => localStorage.getItem(LS_KEY) || "");
  const [guestEmail, setGuestEmail]       = useState(() => localStorage.getItem(LS_EMAIL) || "");
  const [showWarnModal, setShowWarnModal] = useState(false);
  const [emailInput, setEmailInput]       = useState("");
  const [emailError, setEmailError]       = useState("");

  // ── UI state ──────────────────────────────────────────────────
  const [copied, setCopied]         = useState(false);
  const [expanded, setExpanded]     = useState({});
  const [codeLang, setCodeLang]     = useState("python");
  const [codeCopied, setCodeCopied] = useState(false);

  // effective key & email for display / code examples
  const activeKey   = user ? apiKey : guestKey;
  const activeEmail = user ? user.email : guestEmail;
  const hasAccess   = !!user || !!guestKey;

  const loadKey = useCallback(async () => {
    if (!user || !supabase) return;
    const { data } = await supabase
      .from("api_keys")
      .select("id, key")
      .eq("user_id", user.id)
      .eq("active", true)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();
    if (data) { setApiKey(data.key); setKeyId(data.id); }
  }, [user]);

  useEffect(() => { loadKey(); }, [loadKey]);

  // ── Guest key generation ──────────────────────────────────────
  function handleContinueWithoutLogin() {
    setShowWarnModal(true);
  }

  function handleGuestGenerate() {
    const trimmed = emailInput.trim();
    if (!trimmed || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(trimmed)) {
      setEmailError("Please enter a valid email address.");
      return;
    }
    const newKey = mkKey(trimmed);
    localStorage.setItem(LS_KEY, newKey);
    localStorage.setItem(LS_EMAIL, trimmed);
    setGuestKey(newKey);
    setGuestEmail(trimmed);
    setShowWarnModal(false);
    setEmailInput("");
    setEmailError("");
  }

  function handleGuestRevoke() {
    localStorage.removeItem(LS_KEY);
    localStorage.removeItem(LS_EMAIL);
    setGuestKey(""); setGuestEmail("");
  }

  // ── Supabase key actions ──────────────────────────────────────
  async function handleGenerateKey() {
    if (!supabase) return;
    setKeyLoading(true); setKeyError("");
    const newKey = mkKey(user.id);
    const { data, error } = await supabase.from("api_keys")
      .insert({ user_id: user.id, key: newKey, active: true })
      .select("id, key").single();
    if (error) { setKeyError(error.message); setKeyLoading(false); return; }
    setApiKey(data.key); setKeyId(data.id); setKeyLoading(false);
  }

  async function handleRegenerate() {
    if (!supabase) return;
    setKeyLoading(true); setKeyError("");
    if (keyId) await supabase.from("api_keys").update({ active: false }).eq("id", keyId);
    const newKey = mkKey(user.id);
    const { data, error } = await supabase.from("api_keys")
      .insert({ user_id: user.id, key: newKey, active: true })
      .select("id, key").single();
    if (error) { setKeyError(error.message); setKeyLoading(false); return; }
    setApiKey(data.key); setKeyId(data.id); setRevokeConfirm(false); setKeyLoading(false);
  }

  async function handleRevoke() {
    if (supabase && keyId) await supabase.from("api_keys").update({ active: false }).eq("id", keyId);
    setApiKey(""); setKeyId(null); setRevokeConfirm(false);
  }

  function copy(text, setter) {
    navigator.clipboard.writeText(text).then(() => { setter(true); setTimeout(() => setter(false), 2000); });
  }

  const displayKey = activeKey || "sdai_xxxxxxxxxxxxxxxxxxxxxxxx_live";

  if (authLoading) return (
    <div className="ap-loading-gate"><div className="spinner" /><p>Loading...</p></div>
  );

  return (
    <div className="ap-root">

      {/* ── Warning modal ─────────────────────────────────── */}
      {showWarnModal && (
        <div className="ap-modal-overlay" onClick={() => setShowWarnModal(false)}>
          <div className="ap-modal" onClick={e => e.stopPropagation()}>
            <div className="ap-modal-icon">⚠️</div>
            <h3 className="ap-modal-title">Your key won't be saved to our servers</h3>
            <p className="ap-modal-body">
              Without an account, your API key is stored <strong>only in this browser</strong>.
              If you clear your browser data, uninstall, or switch devices — <strong>the key is gone forever</strong> and cannot be recovered.
            </p>
            <p className="ap-modal-body">Enter your email so you can identify this key. We will not spam you.</p>
            <input
              className={`ap-modal-input${emailError ? " ap-input-error" : ""}`}
              type="email"
              placeholder="you@example.com"
              value={emailInput}
              onChange={e => { setEmailInput(e.target.value); setEmailError(""); }}
              onKeyDown={e => e.key === "Enter" && handleGuestGenerate()}
            />
            {emailError && <p className="ap-modal-error">{emailError}</p>}
            <div className="ap-modal-actions">
              <button className="ap-btn-primary" onClick={handleGuestGenerate}>Generate my API key</button>
              <button className="ap-btn-text" onClick={() => { setShowWarnModal(false); setEmailError(""); }}>Cancel</button>
            </div>
            <p className="ap-modal-login-hint">
              Want your key saved safely?{" "}
              <button className="ap-link-btn" onClick={() => { setShowWarnModal(false); navigate("/login", { state: { from: "/api" } }); }}>
                Sign in / Sign up free →
              </button>
            </p>
          </div>
        </div>
      )}

      {/* ── Hero ─────────────────────────────────────────── */}
      <div className="ap-hero">
        <div className="ap-hero-glow ap-glow-1" />
        <div className="ap-hero-glow ap-glow-2" />
        <div className="ap-hero-inner">
          <p className="ap-eyebrow">Developer Access</p>
          <h1 className="ap-h1">SpaceDebrisAI<br /><span className="ap-h1-accent">Public API</span></h1>
          <p className="ap-sub">Real-time satellite positions, proximity risk classifications, and AI-generated avoidance maneuvers — all via a simple REST API. Built on SGP4 propagation over <strong style={{color:"#fff"}}>500 tracked objects</strong>.</p>
          <div className="ap-badges">
            <span className="ap-badge">REST</span>
            <span className="ap-badge">JSON</span>
            <span className="ap-badge">Free tier</span>
            <span className="ap-badge ap-badge-live">● Live data</span>
          </div>
          {activeEmail && (
            <div className="ap-user-pill">
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><circle cx="7" cy="4.5" r="2.5" stroke="currentColor" strokeWidth="1.3"/><path d="M1.5 12.5c0-3.036 2.462-5.5 5.5-5.5s5.5 2.464 5.5 5.5" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/></svg>
              <span>{activeEmail}</span>
              {user
                ? <button className="ap-signout-btn" onClick={signOut}>Sign out</button>
                : <button className="ap-signout-btn" onClick={handleGuestRevoke}>Clear key</button>
              }
              {!user && <span className="ap-guest-badge">Guest</span>}
            </div>
          )}
        </div>
      </div>

      <div className="ap-body">

        {/* ── 01 API key ───────────────────────────────────── */}
        <section className="ap-section">
          <div className="ap-section-label-row">
            <span className="ap-section-num">01</span>
            <h2 className="ap-section-title">Your API key</h2>
          </div>

          {/* ── Not logged in, no guest key: choice gate ── */}
          {!hasAccess && (
            <div className="ap-key-card ap-choice-card">
              <p className="ap-choice-title">Get your free API key</p>
              <p className="ap-choice-sub">Choose how you'd like to access the API.</p>
              <div className="ap-choice-grid">
                <div className="ap-choice-option ap-choice-recommended">
                  <div className="ap-choice-badge-top">Recommended</div>
                  <div className="ap-choice-icon">🔐</div>
                  <h4>Sign in / Sign up</h4>
                  <p>Your key is saved to your account. Access it from any device, anytime.</p>
                  <button className="ap-btn-primary" onClick={() => navigate("/login", { state: { from: "/api" } })}>
                    Sign in / Sign up free
                  </button>
                </div>
                <div className="ap-choice-option">
                  <div className="ap-choice-icon">⚡</div>
                  <h4>Continue without account</h4>
                  <p>Get a key instantly. Stored only in this browser — you may lose it if you clear data.</p>
                  <button className="ap-btn-outline" onClick={handleContinueWithoutLogin}>
                    Continue without login
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* ── Logged in: Supabase-backed key ── */}
          {user && (
            <div className="ap-key-card">
              {keyError && <p className="ap-key-error">{keyError}</p>}
              {!apiKey ? (
                <div className="ap-key-empty">
                  <div className="ap-key-placeholder-icon">
                    <svg width="40" height="40" viewBox="0 0 40 40" fill="none"><circle cx="15" cy="15" r="9" stroke="var(--accent)" strokeWidth="1.5"/><circle cx="15" cy="15" r="4" fill="none" stroke="var(--accent)" strokeWidth="1.5"/><path d="M21.5 21.5 L35 35" stroke="var(--accent)" strokeWidth="2" strokeLinecap="round"/><circle cx="29" cy="31" r="2" fill="var(--accent)" opacity="0.6"/><circle cx="33" cy="35" r="1.5" fill="var(--accent)" opacity="0.4"/></svg>
                  </div>
                  <p className="ap-key-empty-text">No API key yet. Generate one to start making live requests.</p>
                  <button className="ap-btn-primary ap-key-gen-btn" onClick={handleGenerateKey} disabled={keyLoading}>
                    {keyLoading ? <span className="btn-spinner" /> : "Generate API key"}
                  </button>
                </div>
              ) : (
                <>
                  <p className="ap-key-intro">Include as <code className="ap-inline-code">X-API-Key</code> header on every authenticated request.</p>
                  <div className="ap-key-display">
                    <div className="ap-key-active-dot" />
                    <span className="ap-key-value">{apiKey}</span>
                    <button className={`ap-btn-copy${copied ? " copied" : ""}`} onClick={() => copy(apiKey, setCopied)}>
                      {copied ? "Copied ✓" : "Copy"}
                    </button>
                  </div>
                  <div className="ap-key-meta">
                    <span className="ap-key-meta-item"><span className="ap-dot ap-dot-green" />Active</span>
                    <span className="ap-key-meta-sep">·</span>
                    <span className="ap-key-meta-item">{user.email}</span>
                  </div>
                  <div className="ap-key-actions">
                    <button className="ap-btn-regen" onClick={handleRegenerate} disabled={keyLoading}>
                      {keyLoading ? <span className="btn-spinner" /> : "↻ Regenerate"}
                    </button>
                    {!revokeConfirm ? (
                      <button className="ap-btn-revoke" onClick={() => setRevokeConfirm(true)}>Revoke key</button>
                    ) : (
                      <div className="ap-revoke-confirm">
                        <span className="ap-revoke-warn">This will delete your key permanently.</span>
                        <button className="ap-btn-revoke-confirm" onClick={handleRevoke}>Yes, revoke</button>
                        <button className="ap-btn-text" onClick={() => setRevokeConfirm(false)}>Cancel</button>
                      </div>
                    )}
                  </div>
                </>
              )}
            </div>
          )}

          {/* ── Guest key active ── */}
          {!user && guestKey && (
            <div className="ap-key-card">
              <div className="ap-guest-key-warn">
                ⚠️ <strong>Guest key</strong> — stored in this browser only. Save it somewhere safe.
              </div>
              <p className="ap-key-intro">Include as <code className="ap-inline-code">X-API-Key</code> header on every authenticated request.</p>
              <div className="ap-key-display">
                <div className="ap-key-active-dot" style={{background:"#f59e0b"}} />
                <span className="ap-key-value">{guestKey}</span>
                <button className={`ap-btn-copy${copied ? " copied" : ""}`} onClick={() => copy(guestKey, setCopied)}>
                  {copied ? "Copied ✓" : "Copy"}
                </button>
              </div>
              <div className="ap-key-meta">
                <span className="ap-key-meta-item"><span className="ap-dot" style={{background:"#f59e0b"}} />Guest</span>
                <span className="ap-key-meta-sep">·</span>
                <span className="ap-key-meta-item">{guestEmail}</span>
              </div>
              <div className="ap-key-actions">
                <button className="ap-btn-regen" onClick={() => { handleGuestRevoke(); setShowWarnModal(true); }}>↻ Regenerate</button>
                <button className="ap-btn-revoke" onClick={handleGuestRevoke}>Clear key</button>
                <button className="ap-btn-primary" style={{marginLeft:"auto"}} onClick={() => navigate("/login", { state: { from: "/api" } })}>
                  Sign in to save key →
                </button>
              </div>
            </div>
          )}
        </section>

        {/* ── 02 Base URL ──────────────────────────────────── */}
        <section className="ap-section">
          <div className="ap-section-label-row">
            <span className="ap-section-num">02</span>
            <h2 className="ap-section-title">Base URL</h2>
          </div>
          <div className="ap-base-url-card">
            <span className="ap-env-pill">PRODUCTION</span>
            <code className="ap-base-code">{BASE}</code>
            <p className="ap-base-note">All endpoints use HTTPS. Pass your key via <code className="ap-inline-code">X-API-Key</code> header.</p>
          </div>
        </section>

        {/* ── 03 Endpoints ─────────────────────────────────── */}
        <section className="ap-section">
          <div className="ap-section-label-row">
            <span className="ap-section-num">03</span>
            <h2 className="ap-section-title">Endpoints</h2>
          </div>
          <div className="ap-endpoints">
            {ENDPOINTS.map((ep) => (
              <div key={ep.path} className={`ap-endpoint${expanded[ep.path] ? " ap-endpoint--open" : ""}`}>
                <button className="ap-endpoint-header" onClick={() => setExpanded(p => ({...p, [ep.path]: !p[ep.path]}))}>
                  <span className="ap-method" style={{color: METHOD_COLOR[ep.method]}}>{ep.method}</span>
                  <span className="ap-path">{ep.path}</span>
                  <span className="ap-endpoint-desc-short">{ep.desc.split(".")[0]}.</span>
                  {ep.auth && <span className="ap-auth-badge" title="Requires X-API-Key">🔑</span>}
                  <span className="ap-expand-icon">{expanded[ep.path] ? "−" : "+"}</span>
                </button>
                {expanded[ep.path] && (
                  <div className="ap-endpoint-body">
                    <p className="ap-endpoint-full-desc">{ep.desc}</p>
                    {ep.auth && (
                      <div className="ap-endpoint-auth-note">
                        Header: <code className="ap-inline-code">X-API-Key: {displayKey}</code>
                      </div>
                    )}
                    {ep.isLink
                      ? <a href={`${BASE}${ep.path}`} target="_blank" rel="noopener noreferrer" className="ap-btn-primary ap-docs-btn">Open Swagger UI →</a>
                      : <><p className="ap-label">Example response</p><pre className="ap-pre">{JSON.stringify(ep.response, null, 2)}</pre></>
                    }
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* ── 04 Code examples ─────────────────────────────── */}
        <section className="ap-section">
          <div className="ap-section-label-row">
            <span className="ap-section-num">04</span>
            <h2 className="ap-section-title">Code examples</h2>
          </div>
          <div className="ap-code-card">
            <div className="ap-code-tabs">
              {["python", "javascript", "curl"].map((lang) => (
                <button key={lang} className={`ap-code-tab${codeLang === lang ? " active" : ""}`} onClick={() => setCodeLang(lang)}>{lang}</button>
              ))}
              <button className="ap-btn-copy ap-code-copy" onClick={() => copy(LANG_CODE[codeLang](displayKey), setCodeCopied)}>
                {codeCopied ? "Copied ✓" : "Copy"}
              </button>
            </div>
            <pre className="ap-pre ap-code-body">{LANG_CODE[codeLang](displayKey)}</pre>
          </div>
        </section>

        {/* ── 05 Rate limits ───────────────────────────────── */}
        <section className="ap-section">
          <div className="ap-section-label-row">
            <span className="ap-section-num">05</span>
            <h2 className="ap-section-title">Rate limits &amp; fair use</h2>
          </div>
          <div className="ap-limits-card">
            <div className="ap-limits-grid">
              <div className="ap-limit-item"><span className="ap-limit-val">60</span><span className="ap-limit-label">req / min</span></div>
              <div className="ap-limit-item"><span className="ap-limit-val">500</span><span className="ap-limit-label">satellites</span></div>
              <div className="ap-limit-item"><span className="ap-limit-val">SGP4</span><span className="ap-limit-label">propagation</span></div>
              <div className="ap-limit-item"><span className="ap-limit-val">Free</span><span className="ap-limit-label">no billing</span></div>
            </div>
            <p className="ap-limits-note">Research &amp; demonstration API. Data refreshed on each request from the onboard TLE database. For production scale, contact the maintainer.</p>
          </div>
        </section>

      </div>
    </div>
  );
}
