import { useState, useEffect, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../contexts/AuthContext";
import { supabase } from "../lib/supabase";

const BASE = "https://virenn77-spacedebrisai.hf.space";

const ENDPOINTS = [
  {
    method: "GET", path: "/health", auth: false,
    desc: "Check whether the SpaceDebrisAI backend is online and healthy.",
    response: { status: "ok", version: "2.0.0" },
  },
  {
    method: "GET", path: "/satellites", auth: true,
    desc: "Real-time geodetic positions (lat, lon, altitude) for all 500 tracked satellites via SGP4 orbital propagation from the onboard TLE database.",
    response: { count: 500, errors: 0, timestamp: "2026-03-11T10:00:00.000Z", satellites: [{ name: "ISS (ZARYA)", lat: 51.62, lon: -12.4, alt_km: 408.5 }] },
  },
  {
    method: "GET", path: "/simulate", auth: true,
    desc: "Full proximity simulation across all 500 tracked satellites. Returns positions, 20 closest approach pairs, AI risk classifications (CRITICAL / MEDIUM / LOW), and recommended avoidance maneuvers.",
    response: { mode: "live", meta: { satellites: 500, pairs_checked: 124750, processing_ms: 312.8 }, closest_pairs: [{ satellites: ["ISS (ZARYA)", "PROGRESS MS-24"], before: { distance_km: 3.12, risk: { level: "CRITICAL", score: 0.97 } }, after: { distance_km: 28.4, risk: { level: "LOW", score: 0.12 } }, maneuver: "Raise apogee by 500 m" }] },
  },
  {
    method: "GET", path: "/tracker/positions", auth: true,
    desc: "Live orbital positions for 20 tracked satellites fetched from N2YO API with 2-minute cache. Includes azimuth and elevation angles.",
    response: { source: "live", satellites: [{ noradId: 25544, name: "ISS (ZARYA)", lat: 51.62, lon: -12.4, alt: 408.5, azimuth: 220.3, elevation: 34.1 }] },
  },
  {
    method: "GET", path: "/docs", auth: false, isLink: true,
    desc: "Interactive Swagger / OpenAPI documentation auto-generated by FastAPI. Try every endpoint directly in your browser.",
    response: null,
  },
];

const METHOD_COLOR = { GET: "#22c55e", POST: "#38bdf8", DELETE: "#ef4444" };

const LANG_CODE = {
  python: (key) => `import requests

API_KEY = "${key}"
BASE    = "${BASE}"
HEADERS = {"X-API-Key": API_KEY}

# All 500 satellite positions
r = requests.get(f"{BASE}/satellites", headers=HEADERS)
sats = r.json()["satellites"]
for s in sats[:5]:
    print(f"{s['name']:30s}  lat={s['lat']:8.3f}  alt={s['alt_km']:.1f} km")

# Proximity simulation
sim = requests.get(f"{BASE}/simulate", headers=HEADERS).json()
for pair in sim["closest_pairs"][:3]:
    a, b = pair["satellites"]
    d    = pair["before"]["distance_km"]
    lvl  = pair["before"]["risk"]["level"]
    print(f"{a} <> {b}: {d:.1f} km  [{lvl}]")`,

  javascript: (key) => `const BASE    = "${BASE}";
const API_KEY = "${key}";
const headers = { "X-API-Key": API_KEY };

// All 500 satellite positions
const { satellites } = await fetch(\`\${BASE}/satellites\`, { headers }).then(r => r.json());
satellites.slice(0, 5).forEach(s =>
  console.log(s.name, s.lat, s.lon, s.alt_km + " km")
);

// Proximity simulation
const sim = await fetch(\`\${BASE}/simulate\`, { headers }).then(r => r.json());
sim.closest_pairs.slice(0, 3).forEach(({ satellites: [a, b], before }) =>
  console.log(\`\${a} <> \${b}: \${before.distance_km} km [\${before.risk.level}]\`)
);`,

  curl: (key) => `# Health check (no auth needed)
curl ${BASE}/health

# 500 satellite positions
curl -H "X-API-Key: ${key}" \\
     ${BASE}/satellites | jq '.satellites[:5]'

# Full proximity simulation
curl -H "X-API-Key: ${key}" \\
     ${BASE}/simulate | jq '{mode,meta,closest_pairs:.closest_pairs[:3]}'`,
};

function mkKey(userId) {
  const ts  = Date.now().toString(16).slice(-8);
  const rnd = Math.floor(Math.random() * 0xffffffffffff).toString(16).padStart(12, "0");
  const uid = userId.replace(/-/g, "").slice(0, 8);
  return `sdai_${uid}${ts}${rnd}_live`;
}

export default function ApiPage() {
  const { user, loading: authLoading, signOut } = useAuth();
  const navigate = useNavigate();

  const [apiKey, setApiKey]         = useState("");
  const [keyId, setKeyId]           = useState(null);
  const [copied, setCopied]         = useState(false);
  const [expanded, setExpanded]     = useState({});
  const [codeLang, setCodeLang]     = useState("python");
  const [codeCopied, setCodeCopied] = useState(false);
  const [revokeConfirm, setRevokeConfirm] = useState(false);
  const [keyLoading, setKeyLoading] = useState(false);
  const [keyError, setKeyError]     = useState("");

  const loadKey = useCallback(async () => {
    if (!user) return;
    const { data } = await supabase
      .from("api_keys")
      .select("id, key")
      .eq("user_id", user.id)
      .eq("active", true)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();
    if (data) { setApiKey(data.key); setKeyId(data.id); }
  }, [user]);

  useEffect(() => { loadKey(); }, [loadKey]);

  if (authLoading) return (
    <div className="ap-loading-gate"><div className="spinner" /><p>Loading...</p></div>
  );

  if (!user) return (
    <div className="ap-auth-gate">
      <div className="ap-auth-card">
        <div className="ap-auth-icon">
          <svg width="52" height="52" viewBox="0 0 52 52" fill="none">
            <circle cx="26" cy="26" r="25" stroke="var(--accent)" strokeWidth="1.5"/>
            <ellipse cx="26" cy="26" rx="25" ry="10" stroke="var(--accent)" strokeWidth="1.5" opacity="0.35"/>
            <circle cx="26" cy="26" r="4.5" fill="var(--accent)"/>
            <circle cx="42" cy="18" r="3" fill="#f87171"/>
            <rect x="19" y="33" width="14" height="12" rx="2.5" fill="none" stroke="var(--text-faint)" strokeWidth="1.5"/>
            <path d="M22 33v-3.5a4 4 0 0 1 8 0V33" stroke="var(--text-faint)" strokeWidth="1.5"/>
          </svg>
        </div>
        <h2 className="ap-auth-title">Sign in to access the API</h2>
        <p className="ap-auth-sub">Create a free account to generate your API key and access all 500 tracked satellites in real time.</p>
        <button className="ap-btn-primary" onClick={() => navigate("/login", { state: { from: "/api" } })}>Sign in / Sign up free</button>
        <p className="ap-auth-note">No credit card required. Free tier includes 60 req/min.</p>
      </div>
    </div>
  );

  async function handleGenerateKey() {
    setKeyLoading(true); setKeyError("");
    const newKey = mkKey(user.id);
    const { data, error } = await supabase.from("api_keys")
      .insert({ user_id: user.id, key: newKey, active: true })
      .select("id, key").single();
    if (error) { setKeyError(error.message); setKeyLoading(false); return; }
    setApiKey(data.key); setKeyId(data.id); setKeyLoading(false);
  }

  async function handleRegenerate() {
    setKeyLoading(true); setKeyError("");
    if (keyId) await supabase.from("api_keys").update({ active: false }).eq("id", keyId);
    const newKey = mkKey(user.id);
    const { data, error } = await supabase.from("api_keys")
      .insert({ user_id: user.id, key: newKey, active: true })
      .select("id, key").single();
    if (error) { setKeyError(error.message); setKeyLoading(false); return; }
    setApiKey(data.key); setKeyId(data.id); setRevokeConfirm(false); setKeyLoading(false);
  }

  async function handleRevoke() {
    if (keyId) await supabase.from("api_keys").update({ active: false }).eq("id", keyId);
    setApiKey(""); setKeyId(null); setRevokeConfirm(false);
  }

  function copy(text, setter) {
    navigator.clipboard.writeText(text).then(() => { setter(true); setTimeout(() => setter(false), 2000); });
  }

  const displayKey = apiKey || "sdai_xxxxxxxxxxxxxxxxxxxxxxxx_live";

  return (
    <div className="ap-root">

      {/* ── Hero ─────────────────────────────────────────── */}
      <div className="ap-hero">
        <div className="ap-hero-glow ap-glow-1" />
        <div className="ap-hero-glow ap-glow-2" />
        <div className="ap-hero-inner">
          <p className="ap-eyebrow">Developer Access</p>
          <h1 className="ap-h1">SpaceDebrisAI<br /><span className="ap-h1-accent">Public API</span></h1>
          <p className="ap-sub">Real-time satellite positions, proximity risk classifications, and AI-generated avoidance maneuvers — all via a simple REST API. Built on SGP4 propagation over <strong style={{color:"#fff"}}>500 tracked objects</strong>.</p>
          <div className="ap-badges">
            <span className="ap-badge">REST</span>
            <span className="ap-badge">JSON</span>
            <span className="ap-badge">Free tier</span>
            <span className="ap-badge ap-badge-live">● Live data</span>
          </div>
          <div className="ap-user-pill">
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><circle cx="7" cy="4.5" r="2.5" stroke="currentColor" strokeWidth="1.3"/><path d="M1.5 12.5c0-3.036 2.462-5.5 5.5-5.5s5.5 2.464 5.5 5.5" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/></svg>
            <span>{user.email}</span>
            <button className="ap-signout-btn" onClick={signOut}>Sign out</button>
          </div>
        </div>
      </div>

      <div className="ap-body">

        {/* ── 01 API key ───────────────────────────────────── */}
        <section className="ap-section">
          <div className="ap-section-label-row">
            <span className="ap-section-num">01</span>
            <h2 className="ap-section-title">Your API key</h2>
          </div>
          <div className="ap-key-card">
            {keyError && <p className="ap-key-error">{keyError}</p>}
            {!apiKey ? (
              <div className="ap-key-empty">
                <div className="ap-key-placeholder-icon">
                  <svg width="40" height="40" viewBox="0 0 40 40" fill="none"><circle cx="15" cy="15" r="9" stroke="var(--accent)" strokeWidth="1.5"/><circle cx="15" cy="15" r="4" fill="none" stroke="var(--accent)" strokeWidth="1.5"/><path d="M21.5 21.5 L35 35" stroke="var(--accent)" strokeWidth="2" strokeLinecap="round"/><circle cx="29" cy="31" r="2" fill="var(--accent)" opacity="0.6"/><circle cx="33" cy="35" r="1.5" fill="var(--accent)" opacity="0.4"/></svg>
                </div>
                <p className="ap-key-empty-text">No API key yet. Generate one to start making live requests.</p>
                <button className="ap-btn-primary ap-key-gen-btn" onClick={handleGenerateKey} disabled={keyLoading}>
                  {keyLoading ? <span className="btn-spinner" /> : "Generate API key"}
                </button>
              </div>
            ) : (
              <>
                <p className="ap-key-intro">Include as <code className="ap-inline-code">X-API-Key</code> header on every authenticated request.</p>
                <div className="ap-key-display">
                  <div className="ap-key-active-dot" />
                  <span className="ap-key-value">{apiKey}</span>
                  <button className={`ap-btn-copy${copied ? " copied" : ""}`} onClick={() => copy(apiKey, setCopied)}>
                    {copied ? "Copied ✓" : "Copy"}
                  </button>
                </div>
                <div className="ap-key-meta">
                  <span className="ap-key-meta-item"><span className="ap-dot ap-dot-green" />Active</span>
                  <span className="ap-key-meta-sep">·</span>
                  <span className="ap-key-meta-item">{user.email}</span>
                </div>
                <div className="ap-key-actions">
                  <button className="ap-btn-regen" onClick={handleRegenerate} disabled={keyLoading}>
                    {keyLoading ? <span className="btn-spinner" /> : "↻ Regenerate"}
                  </button>
                  {!revokeConfirm ? (
                    <button className="ap-btn-revoke" onClick={() => setRevokeConfirm(true)}>Revoke key</button>
                  ) : (
                    <div className="ap-revoke-confirm">
                      <span className="ap-revoke-warn">This will delete your key permanently.</span>
                      <button className="ap-btn-revoke-confirm" onClick={handleRevoke}>Yes, revoke</button>
                      <button className="ap-btn-text" onClick={() => setRevokeConfirm(false)}>Cancel</button>
                    </div>
                  )}
                </div>
              </>
            )}
          </div>
        </section>

        {/* ── 02 Base URL ──────────────────────────────────── */}
        <section className="ap-section">
          <div className="ap-section-label-row">
            <span className="ap-section-num">02</span>
            <h2 className="ap-section-title">Base URL</h2>
          </div>
          <div className="ap-base-url-card">
            <span className="ap-env-pill">PRODUCTION</span>
            <code className="ap-base-code">{BASE}</code>
            <p className="ap-base-note">All endpoints use HTTPS. Pass your key via <code className="ap-inline-code">X-API-Key</code> header.</p>
          </div>
        </section>

        {/* ── 03 Endpoints ─────────────────────────────────── */}
        <section className="ap-section">
          <div className="ap-section-label-row">
            <span className="ap-section-num">03</span>
            <h2 className="ap-section-title">Endpoints</h2>
          </div>
          <div className="ap-endpoints">
            {ENDPOINTS.map((ep) => (
              <div key={ep.path} className={`ap-endpoint${expanded[ep.path] ? " ap-endpoint--open" : ""}`}>
                <button className="ap-endpoint-header" onClick={() => setExpanded(p => ({...p, [ep.path]: !p[ep.path]}))}>
                  <span className="ap-method" style={{color: METHOD_COLOR[ep.method]}}>{ep.method}</span>
                  <span className="ap-path">{ep.path}</span>
                  <span className="ap-endpoint-desc-short">{ep.desc.split(".")[0]}.</span>
                  {ep.auth && <span className="ap-auth-badge" title="Requires X-API-Key">🔑</span>}
                  <span className="ap-expand-icon">{expanded[ep.path] ? "−" : "+"}</span>
                </button>
                {expanded[ep.path] && (
                  <div className="ap-endpoint-body">
                    <p className="ap-endpoint-full-desc">{ep.desc}</p>
                    {ep.auth && (
                      <div className="ap-endpoint-auth-note">
                        Header: <code className="ap-inline-code">X-API-Key: {displayKey}</code>
                      </div>
                    )}
                    {ep.isLink
                      ? <a href={`${BASE}${ep.path}`} target="_blank" rel="noopener noreferrer" className="ap-btn-primary ap-docs-btn">Open Swagger UI →</a>
                      : <><p className="ap-label">Example response</p><pre className="ap-pre">{JSON.stringify(ep.response, null, 2)}</pre></>
                    }
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* ── 04 Code examples ─────────────────────────────── */}
        <section className="ap-section">
          <div className="ap-section-label-row">
            <span className="ap-section-num">04</span>
            <h2 className="ap-section-title">Code examples</h2>
          </div>
          <div className="ap-code-card">
            <div className="ap-code-tabs">
              {["python", "javascript", "curl"].map((lang) => (
                <button key={lang} className={`ap-code-tab${codeLang === lang ? " active" : ""}`} onClick={() => setCodeLang(lang)}>{lang}</button>
              ))}
              <button className="ap-btn-copy ap-code-copy" onClick={() => copy(LANG_CODE[codeLang](displayKey), setCodeCopied)}>
                {codeCopied ? "Copied ✓" : "Copy"}
              </button>
            </div>
            <pre className="ap-pre ap-code-body">{LANG_CODE[codeLang](displayKey)}</pre>
          </div>
        </section>

        {/* ── 05 Rate limits ───────────────────────────────── */}
        <section className="ap-section">
          <div className="ap-section-label-row">
            <span className="ap-section-num">05</span>
            <h2 className="ap-section-title">Rate limits &amp; fair use</h2>
          </div>
          <div className="ap-limits-card">
            <div className="ap-limits-grid">
              <div className="ap-limit-item"><span className="ap-limit-val">60</span><span className="ap-limit-label">req / min</span></div>
              <div className="ap-limit-item"><span className="ap-limit-val">500</span><span className="ap-limit-label">satellites</span></div>
              <div className="ap-limit-item"><span className="ap-limit-val">SGP4</span><span className="ap-limit-label">propagation</span></div>
              <div className="ap-limit-item"><span className="ap-limit-val">Free</span><span className="ap-limit-label">no billing</span></div>
            </div>
            <p className="ap-limits-note">Research &amp; demonstration API. Data refreshed on each request from the onboard TLE database. For production scale, contact the maintainer.</p>
          </div>
        </section>

      </div>
    </div>
  );
}
