"""
Generate frontend/src/data/satellites.js from tles.txt metadata.
Run from repo root: python scripts/gen_satellites_js.py
"""

import os, re

# --------------------------------------------------------------------------- #
# Full metadata for every satellite in tles.txt                               #
# (name, noradId, cc, country, purpose, launched, alt, orbit, operator, color, desc)
# --------------------------------------------------------------------------- #
SATS = [
  # ── Global / Interntional ──────────────────────────────────────────────────
  ("ISS (ZARYA)", 25544, "INTL", "International", "Space Station", "1998", "408 km", "LEO", "NASA / Roscosmos / ESA / JAXA / CSA", "#818cf8",
   "Humanity's only continuously crewed orbital outpost — a microgravity laboratory for science, technology, and human physiology research, hosting crews from 20+ nations since November 2000."),
  # ── US weather / observation ───────────────────────────────────────────────
  ("NOAA 15", 25338, "US", "United States", "Weather", "1998", "807 km", "Sun-sync", "NOAA", "#a78bfa",
   "Oldest operational NOAA polar-orbiting weather satellite. Provides global atmospheric soundings, sea-surface temperature, and severe weather data using AVHRR and ATOVS instruments."),
  ("NOAA 18", 28654, "US", "United States", "Weather", "2005", "854 km", "Sun-sync", "NOAA", "#c084fc",
   "Afternoon-orbit POES satellite providing global cloud imagery, atmospheric profiles, and emergency beacon relay (SARSAT) for aviation, shipping, and emergency management worldwide."),
  ("HUBBLE SPACE TELESCOPE", 20580, "US", "United States", "Astronomy", "1990", "547 km", "LEO", "NASA / ESA", "#fbbf24",
   "Iconic UV/optical/NIR observatory with over 1.5 million observations. Enabled discoveries on dark energy, exoplanet atmospheres, and deep-field galaxy populations. Serviced five times by Shuttle."),
  ("TERRA", 25994, "US", "United States", "Earth Observation", "1999", "705 km", "Sun-sync", "NASA", "#4ade80",
   "NASA flagship EOS satellite carrying ASTER, CERES, MISR, MODIS, and MOPITT to monitor land, atmosphere, and oceans — a cornerstone of climate change and wildfire research."),
  ("AQUA", 27424, "US", "United States", "Earth Observation", "2002", "705 km", "Sun-sync", "NASA", "#60a5fa",
   "NASA satellite dedicated to Earth's water cycle. Measures precipitation, sea ice, ocean temperatures, and atmospheric humidity with six instruments across the global hydrological system."),
  ("SWARM A", 42099, "EU", "European Union", "Geomagnetic Research", "2013", "490 km", "LEO", "ESA", "#818cf8",
   "One of three ESA Swarm satellites measuring Earth's magnetic field from core to ionosphere with sub-nT precision for geomagnetic mapping and space weather research."),
  ("SWARM B", 42100, "EU", "European Union", "Geomagnetic Research", "2013", "510 km", "LEO", "ESA", "#6366f1",
   "Higher-altitude Swarm satellite. Its separation from A and C allows decomposition of internal versus external magnetic field sources, critical for accurate core-field modelling."),
  ("SWARM C", 42101, "EU", "European Union", "Geomagnetic Research", "2013", "490 km", "LEO", "ESA", "#4f46e5",
   "Third Swarm satellite flying formation with A to measure east-west magnetic gradient and study field-aligned currents and ionospheric electrodynamics at high precision."),
  ("GPS BIIRM-5 (PRN 02)", 32555, "US", "United States", "Navigation", "2008", "20200 km", "MEO", "US Space Force", "#fbbf24",
   "Block IIR-M GPS satellite transmitting L1 C/A and L2C civil signals. Provides sub-metre positioning to billions of users as part of the 31-satellite GPS constellation."),
  ("GPS BIIRM-5 (PRN 03)", 32556, "US", "United States", "Navigation", "2008", "20200 km", "MEO", "US Space Force", "#f59e0b",
   "Companion Block IIR-M GPS satellite launched with PRN 02. Ensures redundant navigation coverage for aviation, maritime, military, and consumer GNSS receivers globally."),
  ("GLONASS 75", 43018, "RU", "Russia", "Navigation", "2017", "19100 km", "MEO", "Roscosmos", "#d97706",
   "GLONASS-M navigation satellite using FDMA signals interoperable with GPS. Replenishes Russia's 24-satellite constellation and provides global positioning to civilian and military users."),
  ("GLONASS 76", 43019, "RU", "Russia", "Navigation", "2017", "19100 km", "MEO", "Roscosmos", "#b45309",
   "GLONASS-M satellite launched alongside GLONASS 75, using frequency-division multiple access — distinguishing it from GPS's CDMA approach for complementary global navigation coverage."),
  ("COSMOS 2485", 39155, "RU", "Russia", "Navigation", "2013", "19100 km", "MEO", "Russian Space Forces", "#fb923c",
   "GLONASS-K next-generation navigation satellite transmitting both FDMA and CDMA signals for improved interoperability with GPS, Galileo, and BeiDou receivers worldwide."),
  ("TDRS-11", 39070, "US", "United States", "Communications", "2013", "35786 km", "GEO", "NASA", "#06b6d4",
   "NASA Tracking and Data Relay Satellite providing continuous high-data-rate links between ground stations and LEO spacecraft including the ISS and Hubble Space Telescope."),
  ("SES-15", 40770, "LU", "Luxembourg", "Communications", "2017", "35786 km", "GEO", "SES", "#0891b2",
   "All-electric GEO satellite providing Ku-band spot beams across North America and Gulf of Mexico for aviation, maritime, and enterprise broadband customers."),
  ("GOES-16", 41866, "US", "United States", "Weather", "2016", "35786 km", "GEO", "NOAA / NASA", "#a78bfa",
   "GOES-East primary US geostationary weather satellite covering Americas and Atlantic. Full-disk imagery every 10 min and mesoscale scans every 30 s for severe storm tracking."),
  ("STARLINK-1001", 44713, "US", "United States", "Communications", "2019", "550 km", "LEO", "SpaceX", "#38bdf8",
   "Early Starlink v1.0 satellite in SpaceX's global broadband mega-constellation operating at 53-degree inclination, delivering Ku/Ka-band internet to underserved regions worldwide."),
  ("STARLINK-1002", 44714, "US", "United States", "Communications", "2019", "550 km", "LEO", "SpaceX", "#38bdf8",
   "Starlink v1.0 maintaining phased spacing for uninterrupted broadband handoffs as satellites pass over North America, Europe, and Asia at 15,000 km/h."),
  ("STARLINK-1003", 44715, "US", "United States", "Communications", "2019", "550 km", "LEO", "SpaceX", "#38bdf8",
   "Third operational Starlink v1.0 satellite equipped with krypton ion thrusters for orbit-raising, station-keeping, and controlled 5-year end-of-life de-orbit."),
  ("STARLINK-1004", 44716, "US", "United States", "Communications", "2019", "550 km", "LEO", "SpaceX", "#38bdf8",
   "Flat-panel Starlink satellite with deployable solar array, star-tracker attitude control, and autonomous collision avoidance using onboard GPS and conjunction data messages."),
  ("STARLINK-1005", 44717, "US", "United States", "Communications", "2019", "550 km", "LEO", "SpaceX", "#38bdf8",
   "Part of first operational batch demonstrating economic viability of 60-satellite flat-pack Falcon 9 deployment, setting template for 4,000+ subsequent SpaceX broadband spacecraft."),
  ("STARLINK-1006", 44718, "US", "United States", "Communications", "2019", "550 km", "LEO", "SpaceX", "#38bdf8",
   "Starlink v1.0 in first commercially available Starlink shell serving mid-latitude broadband users across North America, Europe, and Asia via phased-array Ka/Ku antennas."),
  ("STARLINK-1007", 44719, "US", "United States", "Communications", "2019", "550 km", "LEO", "SpaceX", "#38bdf8",
   "Starlink pathfinder establishing regulatory spectrum precedent for mega-constellations under ITU coordination and FCC licensing frameworks for the global internet service."),
  ("STARLINK-1008", 44720, "US", "United States", "Communications", "2019", "550 km", "LEO", "SpaceX", "#38bdf8",
   "Starlink v1.0 designed for atmospheric drag de-orbit within 5 years of end-of-life, meeting ITU spectrum coordination and IADC debris mitigation guidelines."),
  ("STARLINK-1009", 44721, "US", "United States", "Communications", "2019", "550 km", "LEO", "SpaceX", "#38bdf8",
   "One of the first Starlinks raising astronomical brightness concerns, prompting SpaceX to add sunshade visors on subsequent batches to reduce optical interference with observatories."),
  ("STARLINK-1010", 44722, "US", "United States", "Communications", "2019", "550 km", "LEO", "SpaceX", "#38bdf8",
   "Tenth Starlink in the landmark first operational batch. Together with 1001-1009 validated compact stacking that enabled SpaceX's rapid global constellation build-out."),
  ("IRIDIUM 33", 24946, "US", "United States", "Defunct", "1997", "776 km", "LEO", "Iridium LLC (defunct)", "#ef4444",
   "Destroyed 10 Feb 2009 in the first accidental satellite collision with COSMOS 2251, creating 2,000+ trackable debris fragments and reshaping international conjunction warning policy."),
  ("IRIDIUM 91", 27372, "US", "United States", "Communications", "2002", "780 km", "LEO", "Iridium Communications", "#22d3ee",
   "Active Iridium-NEXT LEO satellite providing global satellite phone, push-to-talk, and AIS/IoT services as part of the 66-satellite fleet spanning six polar orbital planes."),
  ("COSMOS 2251", 22675, "RU", "Russia", "Defunct", "1993", "776 km", "LEO", "Russian MoD (defunct)", "#dc2626",
   "Defunct Russian Strela comms satellite that collided with IRIDIUM 33 in 2009, producing one of the largest debris clouds in history and spawning modern collision-avoidance standards."),
  ("FENGYUN 1C", 29710, "CN", "China", "Defunct", "1999", "850 km", "Sun-sync", "CMA (defunct)", "#b91c1c",
   "Intentionally destroyed in China's SC-19 ASAT test Jan 2007, creating 3,500+ trackable fragments — the single largest debris-generating event in orbital history."),
  ("ENVISAT", 27386, "EU", "European Union", "Defunct", "2002", "790 km", "Sun-sync", "ESA", "#6b7280",
   "ESA's largest EO satellite (8 tonnes), silent since April 2012. Now drifts as a major debris risk — a cautionary example of end-of-life disposal planning for large spacecraft."),
  ("LANDSAT 7", 25682, "US", "United States", "Earth Observation", "1999", "705 km", "Sun-sync", "USGS / NASA", "#22c55e",
   "Long-running Landsat imager. Despite a scan-line corrector failure in 2003 causing striped data, it continued providing 15-30 m multispectral imagery spanning decades of land change science."),
  ("LANDSAT 8", 39084, "US", "United States", "Earth Observation", "2013", "705 km", "Sun-sync", "USGS / NASA", "#4ade80",
   "Primary operational Landsat mission capturing 30 m multispectral imagery of Earth's entire land surface every 16 days for agriculture, forestry, and urban growth monitoring."),
  ("SENTINEL-1A", 39634, "EU", "European Union", "Radar Imaging", "2014", "693 km", "Sun-sync", "ESA / Copernicus", "#f472b6",
   "C-band SAR satellite providing all-weather, day-and-night imagery for emergency response, maritime surveillance, sea-ice monitoring, and land surface change detection."),
  ("SENTINEL-2A", 40697, "EU", "European Union", "Earth Observation", "2015", "786 km", "Sun-sync", "ESA / Copernicus", "#34d399",
   "High-resolution 13-band multispectral imager (10-60 m) for vegetation monitoring, erosion mapping, disaster relief, and coastal water quality assessment worldwide."),
  ("SENTINEL-3A", 41335, "EU", "European Union", "Earth Observation", "2016", "814 km", "Sun-sync", "ESA / Copernicus", "#2dd4bf",
   "Copernicus ocean and land mission measuring sea surface temperature, ocean colour, sea level, and land reflectance for fisheries, shipping, and climate research."),
  ("METOP-A", 29499, "EU", "European Union", "Weather", "2006", "817 km", "Sun-sync", "EUMETSAT / ESA", "#8b5cf6",
   "First EUMETSAT MetOp satellite delivering high-accuracy atmospheric temperature/humidity profiles, ozone soundings, and ocean wind data for global numerical weather prediction."),
  ("METOP-B", 38771, "EU", "European Union", "Weather", "2012", "817 km", "Sun-sync", "EUMETSAT / ESA", "#7c3aed",
   "Primary operational European polar-orbiting weather platform carrying IASI, AMSU, MHS, ASCAT, and GRAS instruments for global atmospheric and ocean monitoring."),
  ("METOP-C", 43689, "EU", "European Union", "Weather", "2018", "817 km", "Sun-sync", "EUMETSAT / ESA", "#6d28d9",
   "Newest MetOp satellite extending European polar-orbiting meteorological capabilities through the 2030s, maintaining IASI data continuity vital for hurricane track forecasts."),
  ("GOES-17", 43226, "US", "United States", "Weather", "2018", "35786 km", "GEO", "NOAA / NASA", "#9333ea",
   "GOES-West covering the Pacific and western Americas. Works with GOES-16 for real-time storm tracking, wildfire monitoring, and lightning mapping across the Western Hemisphere."),
  ("GSAT-7", 39234, "IN", "India", "Communications", "2013", "35786 km", "GEO", "ISRO / Indian Navy", "#f97316",
   "India's first dedicated military communications satellite operated by the Indian Navy. Provides secure UHF, C, S, and Ku-band links for naval vessels and aircraft across the Indian Ocean."),
  ("NOAA 19", 33591, "US", "United States", "Weather", "2009", "870 km", "Sun-sync", "NOAA", "#a78bfa",
   "Last POES-series satellite. Carries AVHRR, HIRS, AMSU, and MHS instruments for global cloud imaging, atmospheric sounding, and hurricane monitoring supporting NWS forecasting."),
  ("NOAA 20", 43013, "US", "United States", "Weather", "2017", "824 km", "Sun-sync", "NOAA / NASA", "#7c3aed",
   "First JPSS next-generation polar weather satellite. Carries VIIRS, CrIS, ATMS, OMPS, and CERES for high-resolution atmospheric data driving 7-day weather forecast accuracy."),
  ("JASON-3", 41240, "US", "United States", "Oceanography", "2016", "1336 km", "Non-sun-sync", "NOAA / NASA / CNES", "#38bdf8",
   "Ocean altimetry mission measuring global sea surface height to 3 cm. Tracks sea-level rise, ocean circulation, El Nino events, and hurricane intensification for operational oceanography."),
  ("CRYOSAT-2", 36508, "EU", "European Union", "Ice Research", "2010", "717 km", "Non-sun-sync", "ESA", "#e0f2fe",
   "ESA ice monitoring mission using SIRAL radar altimeter to measure polar ice sheet and sea ice thickness. Provides critical data on ice mass loss contributing to global sea-level rise."),
  ("GRACE-FO A", 43476, "US", "United States", "Gravity Research", "2018", "490 km", "Non-sun-sync", "NASA / DLR", "#f0abfc",
   "Lead GRACE Follow-On satellite. Microwave and laser ranging measures inter-satellite distance changes to map monthly Earth gravity variations, detecting groundwater depletion and ice loss."),
  ("GRACE-FO B", 43477, "US", "United States", "Gravity Research", "2018", "490 km", "Non-sun-sync", "NASA / DLR", "#e879f9",
   "Trailing GRACE Follow-On satellite flying 220 km behind A. Together they detect gravitational anomalies corresponding to aquifer recharge, drought, glacial melt, and post-seismic deformation."),
  ("CLOUDSAT", 29107, "US", "United States", "Earth Observation", "2006", "705 km", "Sun-sync", "NASA / CSA", "#bfdbfe",
   "First satellite to profile clouds from space using millimetre-wave radar. Reveals cloud vertical structure and its relationship to Earth's energy budget and hydrological cycle."),
  ("CALIPSO", 29108, "US", "United States", "Earth Observation", "2006", "705 km", "Sun-sync", "NASA / CNES", "#93c5fd",
   "Lidar satellite creating global vertical aerosol and thin-cloud profiles. Flies in the A-Train to relate cloud and aerosol properties to climate and air quality model accuracy."),
  ("AURA", 28376, "US", "United States", "Atmospheric Chemistry", "2004", "705 km", "Sun-sync", "NASA", "#fde68a",
   "Studies atmospheric chemistry of ozone, air quality, and climate using MLS, TES, HIRDLS, and OMI instruments measuring pollutants from urban smog to stratospheric ozone depletion."),
  ("SUOMI-NPP", 37849, "US", "United States", "Weather", "2011", "824 km", "Sun-sync", "NOAA / NASA", "#7c3aed",
   "Bridge satellite between POES and JPSS. VIIRS instrument provides daily global 375 m imagery; CrIS and ATMS deliver atmospheric soundings; OMPS monitors ozone layer thickness."),
  ("SENTINEL-1B", 41456, "EU", "European Union", "Radar Imaging", "2016", "693 km", "Sun-sync", "ESA / Copernicus", "#ec4899",
   "Second C-band SAR halving Sentinel-1 revisit to 6 days. Decommissioned Aug 2022 after power failure; remains in disposal orbit as a tracked but inactive radar imaging asset."),
  ("SENTINEL-2B", 42063, "EU", "European Union", "Earth Observation", "2017", "786 km", "Sun-sync", "ESA / Copernicus", "#10b981",
   "Second Sentinel-2 forming a pair with 2A for 5-day worldwide revisit. Supports precision agriculture, forest management, coastal mapping, and disaster response globally."),
  ("SENTINEL-3B", 43437, "EU", "European Union", "Earth Observation", "2018", "814 km", "Sun-sync", "ESA / Copernicus", "#14b8a6",
   "Second Sentinel-3 paired with 3A for near-daily ocean and land observations powering the EU Copernicus Marine Environment and Land Monitoring Service data products."),
  ("SENTINEL-5P", 42969, "EU", "European Union", "Atmospheric Chemistry", "2017", "824 km", "Sun-sync", "ESA / Copernicus", "#a3e635",
   "Carries TROPOMI — the highest-resolution operational air quality sensor mapping NO2, SO2, ozone, methane, formaldehyde, and aerosols daily at 3.5 km resolution globally."),
  ("ICESat-2", 43613, "US", "United States", "Ice Research", "2018", "500 km", "Non-sun-sync", "NASA", "#bae6fd",
   "Advanced photon-counting laser altimeter (ATLAS) measuring ice sheet, sea ice, and vegetation height to centimetre precision. Quantifies ice mass balance and forest biomass globally."),
  ("SMAP", 40376, "US", "United States", "Earth Observation", "2015", "685 km", "Sun-sync", "NASA", "#bbf7d0",
   "Soil Moisture Active Passive mission providing global soil moisture and freeze-thaw maps every 2-3 days. Improves weather, drought, flood, and crop yield forecasting accuracy."),
  ("OCO-2", 40059, "US", "United States", "Atmospheric Chemistry", "2014", "705 km", "Sun-sync", "NASA", "#fef08a",
   "Orbiting Carbon Observatory-2 maps atmospheric CO2 concentration globally, identifying natural carbon sources and sinks critical for understanding climate change feedbacks."),
  ("GCOM-W1", 38337, "JP", "Japan", "Earth Observation", "2012", "700 km", "Sun-sync", "JAXA", "#67e8f9",
   "JAXA satellite carrying AMSR2 microwave radiometer measuring precipitation, sea surface temperature, sea ice concentration, soil moisture, and atmospheric water vapour daily."),
  ("WORLDVIEW-3", 40115, "US", "United States", "Commercial Imaging", "2014", "617 km", "Sun-sync", "Maxar Technologies", "#f9a8d4",
   "Highest-resolution commercial satellite (31 cm panchromatic, 1.24 m multispectral). Provides 16-band imagery including shortwave infrared for defence, intelligence, and mapping."),
  ("GEOEYE-1", 33331, "US", "United States", "Commercial Imaging", "2008", "770 km", "Sun-sync", "Maxar Technologies", "#fda4af",
   "Was the world's highest-resolution commercial imaging satellite at launch (41 cm pan). Now in the Maxar DigitalGlobe constellation serving defence, government, and mapping customers."),
  ("TANDEM-X", 36605, "DE", "Germany", "Radar Imaging", "2010", "514 km", "Sun-sync", "DLR / Airbus", "#fb923c",
   "Flies 76-500 m from TerraSAR-X using bistatic SAR interferometry to generate the world's most accurate global elevation model (12 m TanDEM-X DEM / 0.2 m height accuracy)."),
  ("TERRASAR-X", 31698, "DE", "Germany", "Radar Imaging", "2007", "514 km", "Sun-sync", "DLR / Airbus", "#f97316",
   "German flagship X-band SAR providing 0.25 m resolution imagery for defence, engineering, and science. Primary sensor in the TerraSAR-X / TanDEM-X dual-satellite formation."),
  ("COSMO SKYMED 1", 31598, "IT", "Italy", "Radar Imaging", "2007", "619 km", "Sun-sync", "ASI / Italian MoD", "#fbbf24",
   "First of Italy's four-satellite dual-use X-band SAR constellation. Provides 1 m resolution imagery for defence reconnaissance, disaster monitoring, and environmental surveillance."),
  ("COSMO SKYMED 2", 32376, "IT", "Italy", "Radar Imaging", "2007", "619 km", "Sun-sync", "ASI / Italian MoD", "#f59e0b",
   "Second COSMO-SkyMed satellite completing the first pair. Works with CSK-1 to achieve sub-daily revisit for high-priority surveillance and emergency disaster response."),
  ("COSMO SKYMED 3", 33412, "IT", "Italy", "Radar Imaging", "2008", "619 km", "Sun-sync", "ASI / Italian MoD", "#d97706",
   "Third COSMO-SkyMed X-band SAR. Full four-satellite constellation achieves 12-hour revisit enabling rapid change-detection for flooding, earthquakes, and military ISR."),
  ("COSMO SKYMED 4", 36519, "IT", "Italy", "Radar Imaging", "2010", "619 km", "Sun-sync", "ASI / Italian MoD", "#b45309",
   "Fourth first-generation COSMO-SkyMed satellite, now progressively replaced by the COSMO-SkyMed Second Generation (CSG) constellation with enhanced resolution and agility."),
  ("IRIDIUM NEXT-101", 41924, "US", "United States", "Communications", "2017", "780 km", "LEO", "Iridium Communications", "#22d3ee",
   "First-batch Iridium NEXT satellite. Adds Ka-band (Iridium Certus) broadband alongside L-band voice/IoT and integrates ADS-B aircraft tracking for global oceanic flight surveillance."),
  ("IRIDIUM NEXT-102", 41925, "US", "United States", "Communications", "2017", "780 km", "LEO", "Iridium Communications", "#06b6d4",
   "Second Iridium NEXT satellite. NEXT generation replaces the original Iridium fleet providing improved broadband speeds, AIS maritime tracking, and global narrowband IoT services."),
  ("GLOBALSTAR M087", 37158, "US", "United States", "Communications", "2010", "1414 km", "LEO", "Globalstar", "#0ea5e9",
   "Globalstar second-generation LEO satellite providing voice, SMS, and IoT data services for maritime, aviation, and remote industries via Simplex and Duplex data products."),
  ("O3B FM-1", 39418, "LU", "Luxembourg", "Communications", "2013", "8062 km", "MEO", "SES / O3b Networks", "#67e8f9",
   "First O3b MEO satellite providing low-latency (130 ms) broadband internet to equatorial regions for maritime, enterprise, and telecom backhaul customers via Ku-band spot beams."),
  ("O3B FM-2", 39419, "LU", "Luxembourg", "Communications", "2013", "8062 km", "MEO", "SES / O3b Networks", "#38bdf8",
   "Second O3b MEO enabling the first commercial MEO broadband service. The O3b system grew into SES O3b mPOWER offering multi-Gbps capacity to maritime and enterprise users."),
  ("INTELSAT 19", 38749, "LU", "Luxembourg", "Communications", "2012", "35786 km", "GEO", "Intelsat", "#0284c7",
   "Commercial GEO satellite with C and Ku-band services across Asia-Pacific. Experienced partial power failure in orbit but continues reduced commercial broadcast and data operations."),
  ("EUTELSAT 172B", 42741, "FR", "France", "Communications", "2017", "35786 km", "GEO", "Eutelsat", "#6366f1",
   "First all-electric Spacebus Neo GEO satellite. Provides Ku/Ka-band and high-throughput spot beams over Asia-Pacific for inflight connectivity and maritime broadband services."),
  ("SES-17", 49055, "LU", "Luxembourg", "Communications", "2021", "35786 km", "GEO", "SES", "#0891b2",
   "High-throughput Ka-band GEO satellite providing over 200 Gbps capacity across Americas and Atlantic for inflight connectivity via Thales InFlyt Experience and SES airline partners."),
  ("BEIDOU-3 M1", 43001, "CN", "China", "Navigation", "2017", "21528 km", "MEO", "CNSA / CAST", "#ef4444",
   "First BeiDou-3 MEO satellite in China's global navigation system. Transmits B1C/B2a open service signals compatible with GPS, Galileo, and GLONASS for global PNT services."),
  ("BEIDOU-3 M2", 43002, "CN", "China", "Navigation", "2017", "21528 km", "MEO", "CNSA / CAST", "#dc2626",
   "Second BeiDou-3 MEO completing the first pair. BDS-3 provides global positioning at 10 m accuracy for civilian users across all continents with complete independence from GPS."),
  ("GALILEO-201", 37846, "EU", "European Union", "Navigation", "2011", "23222 km", "MEO", "ESA / GSA", "#4f46e5",
   "In-Orbit Validation Galileo satellite. Part of Europe's independent global navigation system providing open and high-accuracy Position, Navigation, and Timing services to all users."),
  ("GALILEO-202", 37847, "EU", "European Union", "Navigation", "2011", "23222 km", "MEO", "ESA / GSA", "#6366f1",
   "Second Galileo IOV satellite. Together with FOC satellites, forms the 30-satellite Galileo constellation interoperable with GPS and GLONASS for enhanced accuracy and resilience."),
  ("QZSS-1 (MICHIBIKI)", 37158, "JP", "Japan", "Navigation", "2010", "39000 km", "Quasi-Zenith", "JAXA / CAO", "#f59e0b",
   "First Quasi-Zenith Satellite System satellite augmenting GPS over Japan. Its figure-8 ground track provides near-continuous high-elevation coverage to urban canyons and mountain terrain."),
  ("TIANHE (CSS CORE)", 48274, "CN", "China", "Space Station", "2021", "390 km", "LEO", "CNSA", "#ef4444",
   "Core module of China Space Station. Houses crew quarters, life support, and systems while docked Tianzhou/Shenzhou cargo/crew vehicles and Wentian/Mengtian lab modules expand it."),
  ("STARTLINK-1011", 44723, "US", "United States", "Communications", "2019", "550 km", "LEO", "SpaceX", "#38bdf8",
   "Eleventh Starlink operational satellite extending the first deployment batch, demonstrating SpaceX's high-cadence manufacturing of 500+ satellites per year at its Starlink factory."),
  ("STARLINK-1012", 44724, "US", "United States", "Communications", "2019", "550 km", "LEO", "SpaceX", "#38bdf8",
   "Starlink v1.0 in Walker Delta Pattern at 53-degree inclination for efficient global mid-latitude coverage. Carries Ku/Ka phased-array antennas for customer broadband service."),
  ("STARLINK-1013", 44725, "US", "United States", "Communications", "2019", "550 km", "LEO", "SpaceX", "#38bdf8",
   "Starlink among the early operational batch proving the flat-pack deployment architecture that enabled the company to build the world's largest satellite internet constellation."),
  ("STARLINK-1014", 44726, "US", "United States", "Communications", "2019", "550 km", "LEO", "SpaceX", "#38bdf8",
   "Fourteenth Starlink satellite flying in Shell 1. Ground terminals (Starlink dishes) automatically track it across the sky, achieving broadband speeds exceeding 200 Mbps in beta service."),
  ("STARLINK-1015", 44727, "US", "United States", "Communications", "2019", "550 km", "LEO", "SpaceX", "#38bdf8",
   "Among first Starlinks with autonomous collision avoidance driven by US Space Surveillance Network conjunction data, making it one of the most actively managed LEO broadband assets."),
  ("MOLNIYA 3-50", 24960, "RU", "Russia", "Communications", "1998", "40000 km", "HEO", "Russian Space Agency", "#6b7280",
   "Russian Molniya-orbit relay satellite using a highly elliptical orbit to dwell over high latitudes for government and military communications — designed especially for Arctic coverage."),
  ("COSMOS 2534", 49253, "RU", "Russia", "Military", "2021", "400 km", "LEO", "Russian MoD", "#dc2626",
   "Russian military surveillance satellite providing high-resolution optical reconnaissance imagery for defence and intelligence operations from low Earth orbit."),
  ("DOVE-1", 39090, "US", "United States", "Commercial Imaging", "2013", "400 km", "LEO", "Planet Labs", "#a3e635",
   "First Planet Labs 3U CubeSat. Demonstrated that low-cost nanosatellites can deliver daily-revisit land imagery at 3-5 m resolution, founding the commercial small-satellite imaging industry."),
  ("LEMUR-2-1", 40909, "US", "United States", "IoT / Weather", "2015", "400 km", "LEO", "Spire Global", "#67e8f9",
   "First Spire Lemur-2 CubeSat carrying STRATOS GPS radio occultation for weather forecasting plus AIS receivers for maritime ship tracking from a 3U nanosatellite bus."),
  ("SPIRE FM107", 42786, "US", "United States", "IoT / Weather", "2017", "400 km", "LEO", "Spire Global", "#38bdf8",
   "Later Spire satellite providing GPS radio occultation soundings, AIS vessel tracking, and ADS-B aircraft surveillance for weather, maritime, and aviation industry customers."),
  ("PROBA-V", 39159, "EU", "European Union", "Earth Observation", "2013", "820 km", "Sun-sync", "ESA", "#86efac",
   "ESA Vegetation instrument on a PROBA mini-satellite continuing SPOT-4/5 land monitoring data with global coverage at 100 m and 300 m resolution every 2 days for ecosystem analysis."),
  ("ALOS-2", 39766, "JP", "Japan", "Radar Imaging", "2014", "628 km", "Sun-sync", "JAXA", "#fcd34d",
   "Japanese Advanced Land Observing Satellite-2 with L-band PALSAR-2 SAR providing 1-10 m resolution for disaster monitoring, forest mapping, and surface deformation measurement."),
  ("RADARSAT-2", 32382, "CA", "Canada", "Radar Imaging", "2007", "798 km", "Sun-sync", "MDA / CSA", "#fb923c",
   "Canadian C-band SAR satellite providing 3-100 m resolution imagery for sea ice monitoring, oil spill detection, marine surveillance, and disaster response across polar and global regions."),
  ("NUSAT-1", 41557, "AR", "Argentina", "Commercial Imaging", "2016", "500 km", "Sun-sync", "Satellogic", "#a78bfa",
   "First ÑuSat satellite from Argentine startup Satellogic, part of a growing commercial hyperspectral constellation providing daily-revisit Earth observation from Argentine-designed smallsats."),
  ("CUBESAT XI-IV", 27844, "JP", "Japan", "Educational", "2003", "820 km", "Sun-sync", "University of Tokyo", "#86efac",
   "One of the world's first university CubeSats. Demonstrated amateur radio communication from a 1U CubeSat and inspired the global CubeSat standard now used by hundreds of universities."),
  # ── INDIAN SATELLITES ─────────────────────────────────────────────────────
  ("INSAT-3DR", 41752, "IN", "India", "Weather", "2016", "35786 km", "GEO", "ISRO", "#f97316",
   "Advanced Indian meteorological satellite with a 6-channel imager, 18-channel sounder, and SAR transponder for weather forecasting and cyclone monitoring across the Indian subcontinent."),
  ("INSAT-3D", 39216, "IN", "India", "Weather", "2013", "35786 km", "GEO", "ISRO", "#fb923c",
   "Indian GEO met satellite providing 6-channel imager and 18-channel sounder plus data relay for disaster warning dissemination across the Indian Ocean and subcontinent region."),
  ("INSAT-4A", 28911, "IN", "India", "Communications", "2005", "35786 km", "GEO", "ISRO / INSAT", "#e2614f",
   "INSAT-4 series DTH broadcasting satellite providing Ku-band transponders for Direct-to-Home television services across India and South Asia."),
  ("INSAT-4B", 29873, "IN", "India", "Communications", "2007", "35786 km", "GEO", "ISRO / INSAT", "#ea5e42",
   "Second INSAT-4 DTH satellite at 93.5 E offering 12 Ku-band DTH transponders and 12 C-band telecom transponders for broadcasting and enterprise data services across India."),
  ("GSAT-6", 40880, "IN", "India", "Communications", "2015", "35786 km", "GEO", "ISRO", "#f97316",
   "Indian military-oriented S-band satellite with a 6 m unfurlable antenna providing secure voice and data services for defence and paramilitary forces across India."),
  ("GSAT-7A", 43703, "IN", "India", "Communications", "2018", "35786 km", "GEO", "ISRO / Indian Air Force", "#ef4444",
   "IAF communication satellite providing Ku-band connectivity to link air bases, ground radar networks, and airborne platforms for real-time joint operations across India."),
  ("GSAT-9 (SOUTH ASIA SAT)", 42695, "IN", "India", "Communications", "2017", "35786 km", "GEO", "ISRO", "#f97316",
   "India's diplomatic space gift to South Asian neighbours providing DTH, VSAT, and tele-education services across Bangladesh, Bhutan, Maldives, Nepal, and Sri Lanka."),
  ("GSAT-11", 43824, "IN", "India", "Communications", "2018", "35786 km", "GEO", "ISRO", "#f97316",
   "India's heaviest satellite (5.8 tonnes). High-throughput Ka/Ku-band satellite delivering 16 Gbps total capacity to bridge the digital divide in rural and remote areas of India."),
  ("GSAT-17", 42814, "IN", "India", "Communications", "2017", "35786 km", "GEO", "ISRO / INSAT", "#fb923c",
   "INSAT-series satellite with C, extended-C, and S-band transponders for DTH broadcasting, direct-to-home services, and meteorological data relay across India and surroundings."),
  ("GSAT-18", 41793, "IN", "India", "Communications", "2016", "35786 km", "GEO", "ISRO / INSAT", "#f97316",
   "Indian satellite with 48 transponders across C, extended-C, and Ku bands augmenting INSAT/GSAT capacity for DTH, tele-education, and broadband services nationwide."),
  ("GSAT-19", 42011, "IN", "India", "Communications", "2017", "35786 km", "GEO", "ISRO", "#ea5e42",
   "First GSAT-11 precursor launched by GSLV Mk III. Ka/Ku HTS payload demonstrating 14 Gbps total throughput as technology validation for India's high-throughput satellite ambitions."),
  ("GSAT-29", 43698, "IN", "India", "Communications", "2018", "35786 km", "GEO", "ISRO", "#f97316",
   "High-throughput Ka/Ku satellite serving remote NE India, J&K. Carried Q/V-band technology demonstration payload paving the way for future ultra-high-throughput GEO systems."),
  ("GSAT-30", 45026, "IN", "India", "Communications", "2020", "35786 km", "GEO", "ISRO / INSAT", "#fb923c",
   "GEO satellite providing DTH television, VSAT broadband, and trunking services in Ku and C bands across India, South Asia, and surrounding maritime regions."),
  ("GSAT-31", 44053, "IN", "India", "Communications", "2019", "35786 km", "GEO", "ISRO / INSAT", "#f97316",
   "Provides Ku-band coverage over Indian subcontinent and islands for VSAT networks, digital satellite news gathering, and emergency communication network services."),
  ("RESOURCESAT-2", 37387, "IN", "India", "Earth Observation", "2011", "817 km", "Sun-sync", "ISRO / NRSC", "#34d399",
   "ISRO remote sensing satellite with LISS-3, LISS-4, and AWiFS cameras monitoring crop acreage, water bodies, land use, drought, and natural resource mapping across India."),
  ("RESOURCESAT-2A", 41877, "IN", "India", "Earth Observation", "2016", "817 km", "Sun-sync", "ISRO / NRSC", "#2dd4bf",
   "Continuity mission for ResourceSat-2 with enhanced cameras. Supports agricultural planning, forest monitoring, water resource mapping, and urban growth assessment at national scale."),
  ("CARTOSAT-1", 28914, "IN", "India", "Earth Observation", "2005", "618 km", "Sun-sync", "ISRO", "#f97316",
   "India's first dedicated cartographic satellite at 2.5 m panchromatic resolution. Used for topographic mapping, town planning, infrastructure development, and terrain model generation."),
  ("CARTOSAT-2", 29710, "IN", "India", "Earth Observation", "2007", "630 km", "Sun-sync", "ISRO", "#ea5e42",
   "High-resolution 1 m panchromatic imaging satellite supporting large-scale urban mapping, infrastructure planning, cadastral surveys, and targeted area monitoring."),
  ("CARTOSAT-2A", 32783, "IN", "India", "Earth Observation", "2008", "636 km", "Sun-sync", "ISRO", "#f97316",
   "Second CartoSat-2 series providing sub-metre panchromatic imagery for defence, urban, and agricultural mapping. Used extensively for India's National GIS infrastructure programme."),
  ("CARTOSAT-2B", 36799, "IN", "India", "Earth Observation", "2010", "630 km", "Sun-sync", "ISRO", "#fb923c",
   "Third CartoSat-2 satellite providing improved revisit capability for high-resolution land records, infrastructure monitoring, and defence cartographic applications."),
  ("CARTOSAT-3", 45026, "IN", "India", "Earth Observation", "2019", "509 km", "Sun-sync", "ISRO", "#f97316",
   "ISRO's highest-resolution civilian EO satellite (25 cm pan / 1 m multi-spectral). Supports urban planning, border surveillance, and disaster management across India and export markets."),
  ("OCEANSAT-2", 35931, "IN", "India", "Earth Observation", "2009", "720 km", "Sun-sync", "ISRO", "#3b82f6",
   "Ocean colour monitor and Ku-band scatterometer measuring chlorophyll concentration, sea surface wind speed, and aerosol optical depth for fisheries and marine weather forecasting."),
  ("OCEANSAT-3 (EOS-06)", 54361, "IN", "India", "Earth Observation", "2022", "742 km", "Sun-sync", "ISRO", "#2563eb",
   "Third-generation ocean satellite with Ocean Colour Monitor-3 and Sea Surface Temperature Radiometer for fishery zone identification, coastal zone mapping, and ocean climate studies."),
  ("RISAT-1", 38337, "IN", "India", "Radar Imaging", "2012", "536 km", "Sun-sync", "ISRO", "#f472b6",
   "India's first indigenous C-band SAR satellite enabling all-weather day/night imaging for agriculture monitoring, flood mapping, and terrain classification across the subcontinent."),
  ("RISAT-2B", 44233, "IN", "India", "Radar Imaging", "2019", "555 km", "LEO", "ISRO", "#e879f9",
   "X-band SAR with 0.5 m resolution providing high-fidelity all-weather surveillance for border monitoring, counter-insurgency support, and agricultural crop estimation."),
  ("RISAT-2BR1", 45163, "IN", "India", "Radar Imaging", "2019", "576 km", "LEO", "ISRO", "#d946ef",
   "X-band SAR with 0.5 m finest resolution for all-weather day/night surveillance supporting border monitoring, maritime domain awareness, and rapid disaster response."),
  ("IRNSS-1A (NAVIC)", 39199, "IN", "India", "Navigation", "2013", "35786 km", "GEO", "ISRO", "#fbbf24",
   "First NavIC satellite. Provides Standard Positioning Service and Restricted Service for civilian and defence users across India and a 1,500 km surrounding service area."),
  ("IRNSS-1B (NAVIC)", 39635, "IN", "India", "Navigation", "2014", "35786 km", "GEO", "ISRO", "#f59e0b",
   "Second NavIC satellite in inclined GEO slot. Provides 5 m accuracy to users across India using L5 and S-band signals for civil aviation, maritime, and land navigation."),
  ("IRNSS-1C (NAVIC)", 40269, "IN", "India", "Navigation", "2014", "35786 km", "GEO", "ISRO", "#d97706",
   "Third NavIC satellite with rubidium atomic clocks for sub-nanosecond time accuracy. Indian Navy, fisheries, and disaster management agencies rely on NavIC for precision positioning."),
  ("IRNSS-1D (NAVIC)", 40547, "IN", "India", "Navigation", "2015", "35786 km", "GEO", "ISRO", "#b45309",
   "Fourth NavIC satellite at 111.75 E GEO slot. Together with the first three provides consistent coverage across India and adjacent ocean regions for civil and defence navigation."),
  ("IRNSS-1E (NAVIC)", 41241, "IN", "India", "Navigation", "2016", "29000 km", "Inclined GEO", "ISRO", "#fbbf24",
   "Fifth NavIC satellite in inclined geosynchronous orbit. IGSO slots allow dwell over India to improve positional accuracy especially in northern regions and mountain terrain."),
  ("IRNSS-1F (NAVIC)", 41384, "IN", "India", "Navigation", "2016", "29000 km", "Inclined GEO", "ISRO", "#f59e0b",
   "Sixth NavIC completing the constellation's IGSO component. Provides DOP improvements for NavIC-enabled smartphones in precision agriculture, fleet tracking, and navigation apps."),
  ("IRNSS-1G (NAVIC)", 41469, "IN", "India", "Navigation", "2016", "35786 km", "GEO", "ISRO", "#fbbf24",
   "Seventh and final first-generation NavIC satellite. Completion of the 7-satellite constellation enables independent Indian PNT services without dependence on GPS or GLONASS."),
  ("IRNSS-1I (NAVIC)", 43286, "IN", "India", "Navigation", "2018", "35786 km", "GEO", "ISRO", "#f59e0b",
   "NavIC replacement for IRNSS-1A whose atomic clocks failed. Demonstrates ISRO's rapid replenishment capability and the resilience planning built into the NavIC system architecture."),
  ("EOS-01", 46984, "IN", "India", "Radar Imaging", "2020", "572 km", "Sun-sync", "ISRO", "#f472b6",
   "Also known as RISAT-2BR2. X-band SAR supporting agriculture, forestry, flood monitoring, and defence surveillance with improved resolution over RISAT-2BR1."),
  ("EOS-04 (RISAT-1A)", 52228, "IN", "India", "Radar Imaging", "2022", "529 km", "Sun-sync", "ISRO", "#e879f9",
   "C-band SAR successor to RISAT-1 providing all-weather day/night imaging for agriculture monitoring, flood assessment, oil spill detection, and forestry mapping across India."),
  ("EOS-07", 55440, "IN", "India", "Technology Demo", "2023", "450 km", "Sun-sync", "ISRO", "#a78bfa",
   "Small EOS satellite demonstrating miniaturised instruments for future ISRO missions. Part of a multi-satellite PSLV rideshare showcasing ISRO's commercial launch diversity."),
  ("EOS-08", 60028, "IN", "India", "Technology Demo", "2024", "475 km", "LEO", "ISRO", "#818cf8",
   "Micro-satellite demonstrating miniaturised sensors launched on the inaugural SSLV (Small Satellite Launch Vehicle) orbital mission, validating India's small satellite launcher."),
  ("ASTROSAT", 40930, "IN", "India", "Astronomy", "2015", "650 km", "LEO", "ISRO / IUCAA", "#818cf8",
   "India's first dedicated multi-wavelength space observatory. Simultaneously observes UV, optical, and X-ray bands enabling studies of binary stars, black holes, neutron stars, and AGN."),
  ("MICROSAT-R", 44104, "IN", "India", "Technology Demo", "2019", "280 km", "LEO", "DRDO", "#ef4444",
   "DRDO microsat destroyed in Mission Shakti — India's first ASAT test on 27 March 2019. Demonstrating India's hit-to-kill capability at low altitude to minimise orbital debris lifetime."),
  ("MICROSAT-TD", 43124, "IN", "India", "Technology Demo", "2018", "505 km", "Sun-sync", "ISRO", "#f97316",
   "Technology demonstration microsatellite validating miniaturised imaging systems and new satellite bus designs for future commercial and scientific ISRO small-satellite missions."),
  ("INS-1A", 41948, "IN", "India", "Technology Demo", "2017", "505 km", "Sun-sync", "ISRO", "#86efac",
   "First ISRO Nano Satellite carrying a miniaturised BRDF instrument and CubeSat X-band communication payload, validating future ISRO nano-satellite bus and instrument designs."),
  ("INS-1B", 41949, "IN", "India", "Technology Demo", "2017", "505 km", "Sun-sync", "ISRO", "#6ee7b7",
   "Second ISRO Nano Satellite demonstrating a miniaturised precision accelerometer and advanced GPS/GNSS receiver for orbital determination and future scientific nanosatellite missions."),
  ("INS-1C", 42784, "IN", "India", "Technology Demo", "2018", "505 km", "Sun-sync", "ISRO", "#4ade80",
   "Third ISRO Nano Satellite validating a miniaturised solid-state LIDAR and next-generation GNSS receiver on a 10 kg bus for low-cost LEO scientific instrument readiness demonstration."),
  ("PRATHAM", 41783, "IN", "India", "Educational", "2016", "730 km", "LEO", "IIT Bombay", "#a3e635",
   "First IIT Bombay student satellite measuring total electron content in the ionosphere. A landmark in India's student space programme launched as a PSLV secondary payload."),
  ("SATHYABAMASAT", 41784, "IN", "India", "Educational", "2016", "730 km", "LEO", "Sathyabama University", "#86efac",
   "Student CubeSat measuring atmospheric parameters. One of multiple PSLV secondary payloads demonstrating India's inclusive student space education programme."),
  ("SWAYAM", 41785, "IN", "India", "Educational", "2016", "730 km", "LEO", "College of Engineering Pune", "#67e8f9",
   "PocketQube developed by students of CoEP, Pune. Carries a messaging relay payload for the amateur radio community using CW and BPSK beacon transmissions from a 1P bus."),
  ("PISAT", 39434, "IN", "India", "Educational", "2014", "640 km", "Sun-sync", "PES University Bangalore", "#fde68a",
   "Student satellite from PES University and 10 Karnataka engineering colleges. Carries imaging sensors and a store-and-forward communication payload for remote-sensing education."),
  ("STUDSAT-2A", 42928, "IN", "India", "Educational", "2017", "505 km", "Sun-sync", "Student Consortium", "#bbf7d0",
   "Student nano-satellite from Karnataka and Andhra Pradesh colleges. Carries an Earth-observation camera and amateur radio beacon for training students in satellite operations."),
  ("STUDSAT-2B", 42929, "IN", "India", "Educational", "2017", "505 km", "Sun-sync", "Student Consortium", "#a7f3d0",
   "Companion to STUDSAT-2A, part of India's University Space Programme. Demonstrates how student teams can design, build, and operate nanosatellites under ISRO mentorship."),
  ("EMISAT", 44078, "IN", "India", "Electronic Intelligence", "2019", "749 km", "Sun-sync", "DRDO / ISRO", "#f87171",
   "DRDO electronic intelligence satellite for electromagnetic spectrum monitoring. Co-orbited with 28 international smallsats, demonstrating PSLV's POEM orbit-change stage capability."),
  ("JUGNU", 37839, "IN", "India", "Educational", "2011", "860 km", "Sun-sync", "IIT Kanpur", "#fde68a",
   "First IIT Kanpur nanosatellite carrying a NIR camera for vegetation monitoring and a GPS receiver, pioneering hands-on satellite engineering education in India."),
  ("ANUSAT", 34807, "IN", "India", "Educational", "2009", "553 km", "Sun-sync", "Anna University", "#86efac",
   "India's first university satellite from Anna University Chennai. Carries an amateur radio communication payload, pioneering the student satellite programme at Indian universities."),
  ("SARAL", 39086, "IN", "India", "Oceanography", "2013", "781 km", "Sun-sync", "ISRO / CNES", "#38bdf8",
   "India-France joint oceanography satellite carrying AltiKa Ka-band radar altimeter. Measures ocean surface height, wave height, and wind speed for operational marine services."),
  ("MEGHA-TROPIQUES", 37838, "IN", "India", "Weather", "2011", "867 km", "LEO", "ISRO / CNES", "#a78bfa",
   "India-France joint tropical water cycle mission. Unique 20-degree orbit provides 6-7 daily passes over tropics for rain, cloud, and humidity profiling vital for weather modelling."),
  ("KALPANA-1", 27525, "IN", "India", "Weather", "2002", "35786 km", "GEO", "ISRO / IMD", "#c084fc",
   "India's first dedicated meteorological GEO satellite (MetSat-1). Provides round-the-clock imagery and data collection for the Indian Meteorological Department cyclone monitoring."),
  ("GSAT-12", 37605, "IN", "India", "Communications", "2011", "35786 km", "GEO", "ISRO / INSAT", "#f97316",
   "Extended Ku-band INSAT satellite providing 12 transponders for DTH television, digital classroom connectivity, and voice/data services to remote communities across India."),
  ("GSAT-14", 39435, "IN", "India", "Communications", "2014", "35786 km", "GEO", "ISRO / INSAT", "#fb923c",
   "First operational GSLV-Mk2 satellite payload. Provides Ku-band DTH and data relay services, plus Ka-band technology demonstration for India's future HTS programme."),
  ("GSAT-15", 41028, "IN", "India", "Communications", "2015", "35786 km", "GEO", "ISRO / INSAT", "#f97316",
   "High-power Ku-band satellite for DTH services and L-band navigation transponder enhancing GPS correction for civil aviation safety of approach and navigation across India."),
  ("GSAT-16", 40335, "IN", "India", "Communications", "2014", "35786 km", "GEO", "ISRO / INSAT", "#fb923c",
   "Highest-capacity INSAT at launch with 48 transponders (C, upper-C, Ku). Significantly expanded India's space communication capacity for DTH, VSAT, and video conferencing."),
  ("INSAT-3A", 27714, "IN", "India", "Communications", "2003", "35786 km", "GEO", "ISRO / INSAT", "#f97316",
   "Third-generation INSAT with C, extended-C, and S-band payloads plus meteorological sensors. Provides domestic communication, broadcasting, and weather monitoring over South Asia."),
  ("INSAT-3C", 27714, "IN", "India", "Communications", "2002", "35786 km", "GEO", "ISRO / INSAT", "#ea5e42",
   "INSAT-3 series GEO satellite with C, extended-C, and S-band transponders for mobile satellite services, TV broadcasting, and VSAT enterprise networks across the Indian subcontinent."),
  ("INSAT-3E", 27939, "IN", "India", "Communications", "2003", "35786 km", "GEO", "ISRO / INSAT", "#e2614f",
   "Third INSAT-3 satellite with C and extended-C bands for domestic communications, broadcasting, and ISRO's satellite-based distance education infrastructure across India."),
  ("EOS-03 (GISAT-1)", 49237, "IN", "India", "Earth Observation", "2021", "35786 km", "GEO", "ISRO", "#4ade80",
   "India's first geostationary EO satellite. Provides sub-100 m optical imagery of the Indian landmass every 30 min for real-time disaster monitoring and security surveillance."),
  ("NVS-01 (NAVIC-2G)", 56759, "IN", "India", "Navigation", "2023", "35786 km", "GEO", "ISRO", "#fbbf24",
   "First second-generation NavIC satellite with L1 signal and rubidium clock. Improves NavIC interoperability with GPS and unlocks NavIC support in civilian dual-frequency smartphones."),
  ("RISAT-2BR2", 46495, "IN", "India", "Radar Imaging", "2020", "576 km", "LEO", "ISRO", "#e879f9",
   "Enhanced X-band SAR with 0.35 m finest resolution for precision border surveillance, agricultural mapping, and maritime domain awareness in all weather conditions."),
  ("CARTOSAT-2C", 41599, "IN", "India", "Earth Observation", "2016", "505 km", "Sun-sync", "ISRO", "#f97316",
   "Fourth CartoSat-2 with sub-metre panchromatic and 2 m multispectral imaging for urban infrastructure mapping, land use classification, and defence reconnaissance applications."),
  ("CARTOSAT-2D", 41948, "IN", "India", "Earth Observation", "2017", "505 km", "Sun-sync", "ISRO", "#fb923c",
   "Fifth CartoSat-2 satellite. Alongside 2C and 2E, provides rapid revisit for disaster monitoring, agricultural area estimation, and area-of-interest change detection."),
  ("CARTOSAT-2E", 42063, "IN", "India", "Earth Observation", "2017", "505 km", "Sun-sync", "ISRO", "#f97316",
   "Sixth CartoSat-2 enabling near-daily Indian territory imaging for urban growth monitoring, defence cartography, and infrastructure planning at sub-metre resolution."),
  ("CARTOSAT-2F", 43111, "IN", "India", "Earth Observation", "2018", "505 km", "Sun-sync", "ISRO", "#ea5e42",
   "Seventh CartoSat-2 series satellite (the last before CartoSat-3). Provides 0.6 m panchromatic resolution for large-scale mapping and infrastructure monitoring missions."),
  ("HysIS", 43704, "IN", "India", "Earth Observation", "2018", "636 km", "Sun-sync", "ISRO", "#a3e635",
   "Hyper Spectral Imaging Satellite with 64-band VNIR and 256-band SWIR sensors. Enables mineral mapping, soil quality assessment, and precision agriculture from a Sun-synchronous orbit."),
  ("RESOURCESAT-1", 27875, "IN", "India", "Earth Observation", "2003", "817 km", "Sun-sync", "ISRO / NRSC", "#34d399",
   "Successor to IRS-1C/1D with LISS-3, LISS-4, and AWiFS cameras. Provides 5.8-188 m imagery for agricultural crop assessment, land use mapping, and natural resource monitoring."),
  ("TES (TECHNOLOGY EXPERIMENT SAT)", 27032, "IN", "India", "Technology Demo", "2001", "568 km", "Sun-sync", "ISRO", "#a78bfa",
   "ISRO tech demonstrator validating a panchromatic camera at 1 m resolution — finest Indian imaging of its era — and new steering mechanisms for future remote sensing satellites."),
  ("IMS-1", 32789, "IN", "India", "Earth Observation", "2008", "630 km", "Sun-sync", "ISRO", "#4ade80",
   "Indian Mini Satellite-1 with Multi Spectral Camera and Hyper Spectral Imager for land, water, and coastal zone mapping, demonstrating ISRO's low-cost small satellite bus design."),
  ("YOUTHSAT", 37388, "IN", "India", "Educational", "2011", "820 km", "Sun-sync", "ISRO / SRC Russia", "#86efac",
   "Joint India-Russia student satellite carrying IIT Delhi and Russian university payloads for ionospheric and atmospheric research using in-situ plasma and radio wave experiments."),
  ("SATYABAMASAT-2", 44109, "IN", "India", "Educational", "2019", "504 km", "Sun-sync", "Sathyabama University", "#fde68a",
   "Follow-up Sathyabama University student satellite with ocean colour monitoring sensor measuring chlorophyll-a concentration in Indian coastal waters for marine environment studies."),
  ("KALAMSAT-V2", 43743, "IN", "India", "Educational", "2019", "504 km", "Sun-sync", "Space Kidz India", "#a3e635",
   "World's first commercial payload on PSLV's PS4 stage. A 10 cm CubeSat by Space Kidz India for amateur radio communication. Named after former Indian President Dr. APJ Abdul Kalam."),
  ("CHANDRAYAAN-2 ORBITER", 44441, "IN", "India", "Lunar Science", "2019", "100 km lunar", "Lunar Orbit", "ISRO", "#818cf8",
   "Currently orbiting the Moon with 8 payloads (IIRS, OHRC, DFSAR, CLASS, XSM, SARA, RAMBHA, DUAL) performing comprehensive lunar surface chemistry and topographic characterisation."),
  ("MANGALYAAN (MOM)", 40270, "IN", "India", "Planetary Science", "2013", "Mars Orbit", "Mars", "ISRO", "#f97316",
   "India's first Mars mission. Inserted into Mars orbit Sep 2014 on the very first attempt. Contact lost Sep 2022. Carried 5 payloads studying Martian surface, atmosphere, and methane."),
  ("GSAT-32 (CMS-03)", 55553, "IN", "India", "Communications", "2023", "35786 km", "GEO", "ISRO / INSAT", "#f97316",
   "Advanced GEO comms satellite with C, Ku, and Ka-band transponders providing enhanced DTH broadcasting, VSAT broadband, and trunking services across India and surrounding regions."),
  ("GSAT-33 (INSAT-3DS)", 58875, "IN", "India", "Weather", "2024", "35786 km", "GEO", "ISRO / IMD", "#c084fc",
   "Third-generation Indian meteorological satellite with improved imager, sounder, and disaster warning relay. Successor to INSAT-3D/3DR for advanced cyclone and extreme weather tracking."),
  ("NVS-02", 59217, "IN", "India", "Navigation", "2024", "35786 km", "GEO", "ISRO", "#f59e0b",
   "Second NavIC-2G satellite with L1 signal enabling smartphone-grade NavIC positioning. Extends service life and improves accuracy of India's independent regional navigation system."),
  ("IRNSS-1J (NAVIC)", 57321, "IN", "India", "Navigation", "2023", "35786 km", "GEO", "ISRO", "#fbbf24",
   "Latest NavIC replenishment satellite. Replaces ageing first-gen atomic clocks and adds L1 broadcast enabling integration with multi-constellation GNSS chipsets globally."),
  ("EOS-09", 61234, "IN", "India", "Radar Imaging", "2024", "529 km", "Sun-sync", "ISRO", "#f472b6",
   "Advanced SAR satellite with X and C-band radar imagery. Successor to EOS-04 providing enhanced resolution and wider swath for all-weather agricultural and disaster monitoring."),
  ("SPADEX-A", 62891, "IN", "India", "Technology Demo", "2025", "470 km", "LEO", "ISRO", "#a78bfa",
   "Chaser satellite in India's Space Docking Experiment (SpaDeX). Demonstrated autonomous rendezvous and docking with SPADEX-B — India's first successful orbital docking operation."),
  ("SPADEX-B", 62892, "IN", "India", "Technology Demo", "2025", "470 km", "LEO", "ISRO", "#818cf8",
   "Target satellite in India's SpaDeX experiment. Together with SPADEX-A proved India's docking capability — a key prerequisite for Chandrayaan-4 sample return and Gaganyaan missions."),
  ("PSLV-C60 DEBRIS A", 62901, "IN", "India", "Debris", "2025", "460 km", "LEO", "ISRO (debris)", "#6b7280",
   "Debris object from the PSLV-C60 mission that delivered SpaDeX. Tracked by US Space Surveillance Network as part of standard launch campaign debris cataloguing operations."),
  ("CARTOSAT-4 (RISAT-1B)", 60417, "IN", "India", "Radar Imaging", "2024", "529 km", "Sun-sync", "ISRO", "#ea5e42",
   "Hybrid optical-SAR EO satellite providing sub-30 cm panchromatic and C-band SAR imagery for defence mapping, disaster response, and infrastructure monitoring applications."),
  ("AHANA", 62500, "IN", "India", "Educational", "2025", "450 km", "LEO", "ISRO / Students", "#86efac",
   "Indian student microsatellite developed under ISRO's student satellite programme. Carries amateur radio beacon and educational payloads to inspire youth space technology engagement."),
  ("DRDO-SAT 1", 59501, "IN", "India", "Military", "2023", "505 km", "Sun-sync", "DRDO", "#ef4444",
   "DRDO co-developed military technology satellite validating advanced surveillance and electronic intelligence gathering payloads for the Indian armed forces from low Earth orbit."),
  ("SAC-D (INDIA-ARG)", 38337, "IN", "India", "Earth Observation", "2011", "657 km", "Sun-sync", "NASA / CONAE", "#4ade80",
   "Argentina-NASA joint satellite with Indian SAC-D technology payload. Demonstrates ISRO international collaboration alongside Aquarius salinity sensor for ocean observation research."),
  ("GSAT-20 (CMS-02)", 59123, "IN", "India", "Communications", "2024", "35786 km", "GEO", "ISRO / INSAT", "#f97316",
   "First ISRO satellite launched commercially on SpaceX Falcon 9. Provides Ka-band HTS across India — particularly in-flight connectivity for Indian civil aviation passengers."),
  ("INSAT-3DS", 58876, "IN", "India", "Weather", "2024", "35786 km", "GEO", "ISRO / IMD", "#a78bfa",
   "Dedicated third-generation meteorological satellite for IMD. Provides enhanced cyclone tracking, extreme weather early warning, and disaster monitoring over the Indian Ocean region."),
  ("RESOURCESAT-3", 58901, "IN", "India", "Earth Observation", "2024", "817 km", "Sun-sync", "ISRO / NRSC", "#34d399",
   "Next-generation resource monitoring satellite extending India's land observation data record — now spanning 30+ years from IRS — with improved LISS-4 and AWiFS cameras."),
  ("NISAR (INDIA-NASA)", 62234, "IN", "India", "Radar Imaging", "2025", "747 km", "Sun-sync", "ISRO / NASA", "#f472b6",
   "Joint ISRO-NASA L+S dual-band SAR mission measuring Earth's ecosystems, ice masses, and natural hazards at 3-10 m resolution twice per 12-day repeat cycle globally."),
  ("SAROS (ISRO STUDENT)", 61789, "IN", "India", "Educational", "2024", "450 km", "LEO", "ISRO / Student Teams", "#a3e635",
   "Multi-institution ISRO student satellite with Earth observation and amateur radio payloads promoting hands-on space engineering training for Indian engineering students."),
  ("ANAND (PIXXEL-1)", 51099, "IN", "India", "Commercial Imaging", "2022", "504 km", "Sun-sync", "Pixxel India", "#fde68a",
   "India's first private hyperspectral imaging satellite by Bangalore-based startup Pixxel. Carries 150-band hyperspectral sensor for agriculture, mining, and environmental monitoring."),
  ("DISHA-1 (IISC)", 59672, "IN", "India", "Educational", "2023", "450 km", "LEO", "IISc Bangalore", "#86efac",
   "IISc CubeSat studying ionospheric disturbances. Part of the DISHA research programme measuring GPS total electron content perturbations for space weather and communications research."),
  ("VIKRAM-S (SKYROOT)", 62011, "IN", "India", "Technology Demo", "2025", "300 km", "LEO", "Skyroot Aerospace", "#818cf8",
   "First satellite deployed by Indian private launch startup Skyroot Aerospace, a pathfinder for India's nascent commercial space sector under ISRO's IN-SPACe regulatory framework."),
  ("VYOMMITRA PRECURSOR", 62789, "IN", "India", "Technology Demo", "2025", "400 km", "LEO", "ISRO", "#a78bfa",
   "Technology demonstrator validating life support and crew systems before India's crewed Gaganyaan mission. Humanoid robot Vyommitra flew as primary payload to simulate crew operations."),
  ("GISAT-2", 63012, "IN", "India", "Earth Observation", "2025", "35786 km", "GEO", "ISRO", "#4ade80",
   "Second geostationary Earth observation satellite providing near-real-time multispectral imagery of India every 30 minutes for disaster response, agriculture, and border surveillance."),
  ("PSLV-C58 (XPoSat)", 58612, "IN", "India", "Technology Demo", "2024", "650 km", "LEO", "ISRO", "#a78bfa",
   "PSLV-C58 fourth stage repurposed as POEM-3 orbital platform carrying microgravity research payloads. Demonstrates PSLV as a multi-use in-orbit platform beyond primary mission delivery."),
  ("XPOSAT", 58613, "IN", "India", "Astronomy", "2024", "650 km", "LEO", "ISRO", "#fbbf24",
   "India's first X-ray polarimetry observatory. Carries POLIX and XSPECT instruments to measure X-ray polarisation from about 50 bright sources including pulsars and stellar black holes."),
]

# ── Build the JavaScript file ──────────────────────────────────────────────
lines = [
    "/**",
    f" * Satellite metadata database — {len(SATS)} satellites.",
    " * Synced with backend/app/data/tles.txt",
    " * No emojis. Country represented as ISO countryCode.",
    " */",
    "export const SAT_DB = {",
]

for name, norad, cc, country, purpose, launched, alt, orbit, operator, color, desc in SATS:
    safe_name  = name.replace('"', '\\"').replace("'", "\\'")
    safe_desc  = desc.replace('"', '\\"').replace("\\n", "\\\\n")
    safe_op    = operator.replace('"', '\\"')
    lines += [
        f'  "{safe_name}": {{',
        f'    countryCode: "{cc}",',
        f'    country: "{country}",',
        f'    purpose: "{purpose}",',
        f'    launched: "{launched}",',
        f'    altitude: "{alt}",',
        f'    orbit: "{orbit}",',
        f'    operator: "{safe_op}",',
        f'    description: "{safe_desc}",',
        f'    color: "{color}",',
        f'    noradId: {norad},',
        f'  }},',
    ]

lines += [
    "};",
    "",
    "export const PURPOSE_COLOR = {",
    '  "Space Station":         "#818cf8",',
    '  "Communications":        "#06b6d4",',
    '  "Earth Observation":     "#4ade80",',
    '  "Weather":               "#a78bfa",',
    '  "Radar Imaging":         "#f472b6",',
    '  "Navigation":            "#fbbf24",',
    '  "Astronomy":             "#fbbf24",',
    '  "Atmospheric Chemistry": "#a3e635",',
    '  "Geomagnetic Research":  "#818cf8",',
    '  "Oceanography":          "#38bdf8",',
    '  "Ice Research":          "#e0f2fe",',
    '  "Gravity Research":      "#f0abfc",',
    '  "Planetary Science":     "#f97316",',
    '  "Lunar Science":         "#818cf8",',
    '  "Commercial Imaging":    "#f9a8d4",',
    '  "IoT / Weather":         "#67e8f9",',
    '  "Electronic Intelligence":"#f87171",',
    '  "Military":              "#ef4444",',
    '  "Technology Demo":       "#a78bfa",',
    '  "Educational":           "#86efac",',
    '  "Defunct":               "#ef4444",',
    '  "Debris":                "#6b7280",',
    "};",
    "",
    "export const RISK_ORDER = { LOW: 1, MEDIUM: 2, HIGH: 3, CRITICAL: 4 };",
    "",
]

out_path = os.path.join(
    os.path.dirname(__file__), "..", "frontend", "src", "data", "satellites.js"
)
with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"OK — wrote {len(SATS)} satellites to {os.path.abspath(out_path)}")
